### ISSUE TITLE
Record food consumption for population

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#10]
We have tables that record food consumption data for people and for households, but there is also need for a third one that records data for food consumption for the population as a whole.

On what administrative levels is this data recorded? Countries? Counties? Enumeration Areas?

**Comment by LuciaSegovia** [comment]
The 'food consumption' at population level is reported at country level. Here's the data source: http://www.fao.org/faostat/en/#data/FBS

**Comment by rbroth** [comment]
I'm assuming that the units for the food will be grams per capita per day?

**Comment by LuciaSegovia** [comment]
kg per capita per year

**Comment by LuciaSegovia** [comment]
Sorry, I forgot to mention. I am currently adding a new variable for Food Balance Sheet (FBS) dataset that it is FoodEx2code. This will be useful later to match between dietary supply and IMPACT model. 

I will add that variable to household survey data as well.

**Comment by LuciaSegovia** [comment]
Hi @rbroth, 

I've just realized that there is a piece of information that needs to be recorded as well: 'source of food'. So, the quantity of food (items) consumed by the household will be disaggregated by: 'own production', 'bought' or 'gifted'.

**Comment by rbroth** [comment]
I assume that only applies to Individual and Household Consumption data, not Country Consumption?

**Comment by LuciaSegovia** [comment]
That's right
