### ISSUE TITLE
Add Enumeration Areas table

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#11]
The enumeration are is where survey givers go to give surveys and record data.

attributes:
- Urban/rural
- in what sub-national admin region is this EA?

**Comment by LuciaSegovia** [comment]
Hi @rbroth , 

I believe that EA is the primary sampling unit for (Demographic Household survey), so at subnational level is the lowest we can get beside household itself. 

I think it something like: Country level>Region>District> Enumeration Area>Household

Maybe there is something in between District and EA.

For attributes, maybe add geographic coordinates? Maybe, we need to add something related to the sampling as well.

**Comment by kmtang** [comment]
Hi both,

Sorry to be late to the party on this, I just realized my GitHub account is registered to my personal email which I have been neglecting the past few weeks.

@LuciaSegovia hit the nail on the head. Just to note that EAs generally are consistent with political boundaries as well so you normally won't find an EA which straddles 2 different districts.

Second the geo-coordinates as well. The coordinate data that we have right now (that is publicly available) is distorted by 5km or less to protect the anonymity of the household. Louise mentioned that she has chatted with the World Bank LSMS team to get the undistorted coordinates for this project, but that has yet to be done yet.
