### ISSUE TITLE
Store the age-gender group options for biomarker aggregation in a dictionary table

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#120]
To allow population of front-end dropdown

**Comment by rbroth** [comment]
@bgsandan  Is there a list of age-gender groups?

**Comment by bgsandan** [comment]
Name | Abbreviation (ID?)
-- | --
Women of reproductive age | WRA
Men | Men
Pre School Children | PSC
School Age Children | SAC

**Comment by andy-bevan** [comment]
In issue #5 I have a spreadsheet which includes 3 age gender groups:

WRA
Pregnant women
children 6-59 months

**Comment by andy-bevan** [comment]
@rbroth 
I guess we are not using dic_ naming convention?
Can I call this table 'demographic' rather than 'age_gender_group'?

**Comment by rbroth** [comment]
No, I haven't used the BGS-style dictionary structure for anything in this project, so also no dic_ naming convention.

`demographic` feels a bit broad. Maybe something more along the lines of `biomarker age_group` or `biomarker_demographic`?

**Comment by fannymawbey** [comment]
> Ok, so it looks like
> 
> * Men
> * WRA
> * Children <60 months (Pre School Children)
> * Children >= 60 months (School Age Children)
> * Pregnant Women
>   Is that correct @fannymawbey ?

Yes that is fine.

**Comment by fannymawbey** [comment]
Also, could we add population groups later? We might have adolescents later on (11-19).
Note that WRA are usually 15-49

**Comment by rbroth** [comment]
@fannymawbey , do I recall correctly: The age definitions for "school age children", "PSC", "WRA", etc. can differ between surveys. E.g. one survey defines WRAs as 15-49, but another might define it as 16-45?
