### ISSUE TITLE
biomarker workflow

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#122]
The workflow of the biomarker data will be as follows:

- frontend makes request to API
- API pulls data from database and calls R scripts
- R script run functions that take array of (demographic data, biomarker data, threshold data, etc.) as parameters and return aggregated result data. 
- aggregated result data is sent to frontend (and cached or something)

Todo: 
- [ ] Ensure that the columns that are currently in the ~`biomarker`~`biomarker_measurement` table capture all biomarker data (as defined by the scientists)
- [ ] create table to store biomarker deficiency thresholds 
- [ ] import deficiency threshold data
- [ ] import biomarker data
- [ ] Create table similar to the micronutrients table (https://github.com/micronutrientsupport/database-architecture/blob/develop/db/objects/micronutrients/V0.1.0.50__micronutrients.sql) that shows the display name, measurement units, etc for each measurement)

**Comment by rbroth** [comment]
Some statements to check for agrrement in understanding
A biomarker survey is very similar to a food consumption surevey. A biomarker survey will:
- have a name
- have a starting date and an end date for when samples are collected, and publication date
- have a survey area that has a geospatial definition (i.e. a polygon that can be drawn on google maps) that defines where the survey was carried out
- collect information about a household, including:
    - the households location as lat/lon (but anonymized, so with added randomness)
    - the household's expenditure
    - the dat ethe interview was collected
- the biomarker survey will also collect information about all the households members (HHM), including:
    - sex
    - date of birth (or age)
    - whether a woman is lactating
    - whether a woman is pregnant
    - whether a child is being breastfed
    -  whether they smoke
    - at what altitude they live (?!)
- one or more samples will be taken from a household member 
- samples can be urine, blood, or breastmilk
- the date when a sample is taken is recorded
- the time when a sample is take is recorded
- it is recorded whether a HHM was fasting before a sample was taken

**Comment by rbroth** [comment]
R scripts:
- For each of the relevant micronutrients (zinc, iodine, iron, etc) there exists an R function that takes as its argument an array of data about samples. 

Each of the array items consists of:
	- demographic information about the person from which the sample was taken (age, sex, is_pregnant, is_smoker, etc.)
	- info about the household (admin-region)
	- time of day when the sample was taken
	- biomarker measurements (ferritin, CRP, etc)

The R function does some calculations and returns an array of values:
	- an adjusted biomarker value (adjusted how and why? For age/sex/etc?)
	- an outlier value (what is this? If it is for a single person, outlier doesn't make sense. If it is for a group, then why does the [fake biomarker data on Teams](https://nercacuk.sharepoint.com/:x:/r/sites/BGSBMGFMAPS/Shared%20Documents/WP4%20-%20Tool%20Development/FakeBiomarkerDataForDev.csv?d=w74867693f1364ac18cf3b1f5e7816e42&csf=1&web=1&e=dh5h2t) have multiple recurring rows?

**Comment by andy-bevan** [comment]
For the above, do the thresholds for deficiency taken as an argument by the R script need to include a greater than/less than qualifier or is that built in the the script already?

**Comment by rbroth** [comment]
> 
> 
> For the above, do the thresholds for deficiency taken as an argument by the R script need to include a greater than/less than qualifier or is that built in the the script already?

I would assume it's already built-in, but @fannymawbey can confirm

**Comment by fannymawbey** [comment]
yes the R script will do that

**Comment by rbroth** [comment]
We want ranges of values: upper and lower

**Comment by rbroth** [comment]
If a micronutrient doesn't have an upper value (e.g. anything above 150 is an excess) will use NULL for the upper threshold

**Comment by andy-bevan** [comment]
I just spotted another possible issue-ette with the thresholds.
For 'Soluble Transferin receptors' it says 'Use threshold given by manufacturer'.
If we want to automate this, will we need a list of manufacturers and the threshold for each?

**Comment by fannymawbey** [comment]
I agree it's quite annoying, but I'm not sure how to do that. I don't have
a list of manufacturers. Would it make sense to use a manufacturer by
default with a predefined threshold value, and if the user works with
another manufacturer, then he will need to enter his own threshold?

Fanny

Le jeu. 22 avr. 2021 à 16:20, andy-bevan ***@***.***> a
écrit :

**Comment by andy-bevan** [comment]
Yes I think that would work if we specify the manufacturer in the threshold type column or conditional info.
