### ISSUE TITLE
Import food composition data

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#123]
We have a bunch of Food Composition Tables (FCT) in teams under channel WP2 --> food composition Tables --> Working files.

We want to import these into the db. Most of the columns correspond to columns in the `fooditem` table, though they will also include the name of the FCt (which should go into the `fct_source` table and possibly data_reference.

**Comment by spenny-liam** [comment]
Would it be worthwhile to make a process that reads the files directly from MS Teams (which stores them in SharePoint) and then insert into the database directly? This would prevent saving multiple versions of the same data (version on teams, downloaded version and then insert scripts sql version), and would mean we could import data dynamically as part of the CI pipeline and automatically pick up new files added to Teams.

For now i will sort out importing the data from local files, with the aim to add on the SharePoint connection later

**Comment by rbroth** [comment]
I think that depends on how much additional work the sharepoint integration will take. If it's a simple matter of suing a pre-existing library and pointing it at the teams folder, then that sounds good.

**Comment by spenny-liam** [comment]
> I think that depends on how much additional work the sharepoint integration will take. If it's a simple matter of using a pre-existing library and pointing it at the teams folder, then that sounds good.

Yes it seems rather simple, just requires an access token. I have emailed sns to ask if that is possible.

**Comment by spenny-liam** [comment]
Related to #138 and #141
