### ISSUE TITLE
Record dataset adjustment status

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#128]
For a survey (in the `survey` table), record whether the data has been adjusted
- for altitude
- for smoking

This data will be used by the biomarker R scripts to see whether they will have to take into account a households altitude and/or a household member's smoking status when calculating micronutrient deficiency

**Comment by rbroth** [comment]
- for altitude
- for smoking

**Comment by rbroth** [comment]
- only haemoglobin data can (currently) be adjusted for altitude
- only haemoglobin data can (currently) be adjusted for smoking
We want to make explicit that it was the haemoglobin measurement that were adjusted, rather than any other measurements

**Comment by rbroth** [comment]
What other adjustments are there @fannymawbey

**Comment by fannymawbey** [comment]
- Ferritin

Adjusted for CRP and AGP  (they are both marker of inflammation)

- Soluble Transferin Receptors (sTfR)

Adjusted for CRP and AGP

- Hemoglobin

Adjusted for Altitude and Smoking

in MyMaps, we will allow the user to adjust other data for inflammation
(RBP for children, zinc) but that's not endorsed by WHO yet, so we won't
put that option in QuickMaps.

**Comment by fannymawbey** [comment]
Just to add that for Ferritin and sTfR, we want to do the adjustment ourselves, we don't want to receive adjusted data from the user. We want to raw data, and the CRP and AGP values per individual to be able to do the adjustment.

**Comment by andy-bevan** [comment]
@rbroth 
Can we clarify - do we just need to record whether incoming data has already been adjusted for variables or do we also need to record whether we have subsequently adjusted it?

**Comment by rbroth** [comment]
I'm assuming it's the former
