### ISSUE TITLE
Biomarker output format

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#134]
in what format does the R function expect the input data? How shall we structure the JSON?

**Comment by rbroth** [comment]
## iron
- age
- is_smoker
- ferritn
- haemoglobin
- altitude_in_meters
- ...

**Comment by fannymawbey** [comment]
I sent a table by mail, let me know if clear and OK

**Comment by bgsandan** [comment]
Hi @fannymawbey  did you also send it to me?  It doesn't seem to have arrived

**Comment by bgsandan** [comment]
Superseded by later work
