### ISSUE TITLE
rename data_reference to citation

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#137]
For the Food Composition Table data, we want to rename the "data_reference" columns to something like "citation", to improve clarity. see #77

**Comment by LuciaSegovia** [comment]
Hi there! In most of INFOODS FCT, they use "bibliography" for the "citation" and "BiblioID" for the "citation_code". I think we can adopt it  🐭

**Comment by rbroth** [comment]
Sounds good/

- [ ] rename `data_reference` to `citation`
- [ ] link `citation` table to `fooditem` table

**Comment by spenny-liam** [comment]
> Sounds good/
> 
> * [ ]  rename `data_reference` to `citation`
> * [ ]  link `citation` table to `fooditem` table

That link already exists

**Comment by LuciaSegovia** [comment]
I meant it the other way around, so change `data_reference` to `bibliography` and `data_reference_original_id` to `biblioID`, but it's fine :)

**Comment by rbroth** [comment]
Ah, just checked. But `fooditem.DATA_REFERENCE_ID` doesn't have a foreign key. And I think we want to either have a many-to-many relationship, or a one-to-many relationship (one fooditem can have many citations)

**Comment by rbroth** [comment]
> I meant it the other way around, so change `data_reference` to `bibliography` and `data_reference_original_id` to `biblioID`, but it's fine :)

Normally a collection of citations is indeed called a bibliography, but in database development we usually name the table after what it contains. Re data_reference_original_id` vs `biblioID`, for our naming convention we want to make clear that this column contains the original id as written on the FCT (e..g "Bobson, 2007" or "[27]"). We will generate our own internl ids for linking the citations to the fooditems

**Comment by LuciaSegovia** [comment]
Ok, that makes sense. Thanks!!
