### ISSUE TITLE
remove food_group table

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#139]
The food-group table is superseded by the food_genus table with food_group as an attribute there

**Comment by spenny-liam** [comment]
Although we agreed on this yesterday. I am now unsure. Would the column food_genus.food_group be unconstrained?

**Comment by spenny-liam** [comment]
There is a table "IMPACT_COMMODITY" with a foreign key to food_group. Should that table be also be removed or should it's foreign key reference food_genus instead?

**Comment by rbroth** [comment]
Constraining the food_group column with a foreign key sounds like a good idea. You'd also have to do the same with the food subgroup. Not urgent, if it's easier at the moment to keep it all in one table feel free to do that.

`Impact_commodity` will need to be constrained with food groups, so I think re-liking it to a food_genus is a good idea. @bgsandan @LuciaSegovia , does it make sense to assign each impact commodity a food_genus?

**Comment by LuciaSegovia** [comment]
Yes, I think that was the idea

**Comment by bgsandan** [comment]
The IMPACT commodities are unlikely to map directly to food\_genus I think as they aren't that specific.  I believe they are derived from the similar FAO categories which will form the food\_group / food\_subgroup of the food\_genus table and eventually linking back to these would be useful.

However we need to get some input from Sherwin as to exactly how this will work.  For now I suggest leaving the food\_group table as an 'orphaned' table just used by the impact commodity table.  We can then update those linkages once we have some clarity on that.

For clarification. The food\_groups linked from the impact\_commodity table will be used in the Projections to 2050 page to display food sources either by individual commodity or aggregated to food groups:

![](https://user-images.githubusercontent.com/39411049/116374934-af584580-a806-11eb-93f1-9b05cb6cb59e.png)

Does this make sense?

**Comment by rbroth** [comment]
@sherwingabr, for reference

**Comment by sherwingabr** [comment]
@bgsandan is right - the food groups in IMPACT are at a more aggregate level than in the food composition table, which are used in the projections page. 

The intention is to better link the IMPACT commodities with foods in the food compositions tables so that, when we get around to the scenarios, we'd be able to recast the projections linking the appropriate food item/group with the relevant IMPACT commodity. We've taken a first stab at harmonising IMPACT commodities with FoodEx2 commodities, but it seems likely easier to link up with the correspondence tables that @LuciaSegovia has set up. I'm guessing this is what you mean @rbroth about assigning a food_genus to each IMPACT commodity. For now, though, I think it's fine to leave the food_group (IMPACT commodities) as orphaned, until we do that mapping.

**Comment by spenny-liam** [comment]
Thank you all. So i will remove the link between fooditem and food_group, but keep the food_group and comodity tables.

food_genus should also get a link to food_group to constrain that column. This will exist as an optional relationship in the structure, as we do not yet have the mappings but we can still implement the design for now.

@rbroth - To resolve the sub_group concept, I suggest an extra column on the food_group table "Parent_ID", where a sub_group would have a parent_id to a group in the same table.

**Comment by rbroth** [comment]
> @rbroth - To resolve the sub_group concept, I suggest an extra column on the food_group table "Parent_ID", where a sub_group would have a parent_id to a group in the same table.

Sounds good. I dimly recall that I didn't do anything fancy with the groups and subgroups because there wasn't a requirement  definition beyond "we want to food groups in order to do aggregate statistics on them". I think it might be worthwhile at some point in the future to clarify who needs food groups and for what purposes, because it sounds like we actually need several different "food groups".
