### ISSUE TITLE
Biomarker data import format

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#142]
We want to agree on a format for importing biomarker data into the system. It should be csv

**Comment by rbroth** [comment]
@fannymawbey , questions about the dataset:
- what is the name? "Malawi DHS survey"?
- Do you have information about the household that these people live in? We assume that every person surveyed lives in ahousehold and that sometimes multiple people live in the same household.
- Has the data been adjusted for altitude and smoking?

**Comment by rbroth** [comment]
- MALARIA_TEST_RESULT - does this mean that the person has had malaria in the last two weeks?

**Comment by rbroth** [comment]
- Can we treat "serum" and "plasma" as synonyms? For example, we store "serum folate" in our system, but the dataset lists "plasma folate"

**Comment by fannymawbey** [comment]
- Malawi MNS 2016
- yes sometimes they live in the same household. We have variables that
allow us to know that. Do you need that?
- Hemoglobin has been adjusted for altitude and smoking for WRA but we
don't have the raw data.

**Comment by fannymawbey** [comment]
It's the result of malaria testing with a Rapid Test Kit. It measures
antigens in the blood at the time of the test, but doesn't tell you when
the person got infected.

There is another question that is self reported - 'Did you have malaria in
the last 2 weeks?', but this is different and we try to avoid using this
one if we actually have a test result.

**Comment by fannymawbey** [comment]
No, we have to be specific. Sometimes they will collect serum, sometimes
plasma, and we need to use the name of the one used by the survey. I think
the idea that we had, as shown in the 'threshold' file, is that you will
have a micronutrient 'folate' and then a matrix 'plasma, serum, red blood
cell, whole blood, urine, breastmilk'.

**Comment by rbroth** [comment]
> - yes sometimes they live in the same household. We have variables that allow us to know that. Do you need that? 
Yes, our data model assumes that we'll know what household a person belongs to. @spenny-liam is working on providing you with a template csv for importing data; that will have all the columns we want

**Comment by andy-bevan** [comment]
Hi @fannymawbey 
I'm looking at defining the import formats for the biomarker survey results data. We already have the survey mentioned above (Malawi MNS 2016). Do you have another example survey we can use?

**Comment by fannymawbey** [comment]
[Ethiopia_National_MNS_report.pdf](https://github.com/micronutrientsupport/database-architecture/files/6615724/Ethiopia_National_MNS_report.pdf)
 you can look at this one, as Ethiopia is also a priority country

**Comment by rbroth** [comment]
Do you have the data for the Ethiopia Survey?

**Comment by andy-bevan** [comment]
I was just going to ask the same thing. The PDF is obviously based on the raw data, but includes lots of charts and tables of aggregated data...

**Comment by fannymawbey** [comment]
Yes we do. I can send via email if that's ok?

**Comment by andy-bevan** [comment]
Yep that's fine.

**Comment by andy-bevan** [comment]
This is the format we would need the data in as a CSV file, ideally:

| Column Header       | Data Type | Values/Format | Description                                                                                                                          | 
|---------------------|-----------|---------------|--------------------------------------------------------------------------------------------------------------------------------------| 
| household_id        | text      |               | An identifier to indicate the household that this person belongs to.                                                                 | 
| person_id           | text      |               | Unique identifier for the person                                                                                                     | 
| sex                 | text      |               | Whether the household member is male or female                                                                                       | 
| education_level     | text      |               | The highest level of education achieved by this person. Can be primary                                                               | 
| age_in_months       | integer   |               | The age of the person at the time of the survey                                                                                      | 
| is_breastfed        | boolean   | "0,1,null"    | "Whether the child is being breastfed; ""true"" indicates that they are"                                                             | 
| is_lactating        | boolean   | "0,1,null"    | "Whether this woman is lactating; ""true"" indicates that she is"                                                                    | 
| is_pregnant         | boolean   | "0,1,null"    | "Whether this woman is pregnant; ""true"" indicates that she is"                                                                     | 
| is_smoker           | boolean   | "0,1,null"    | Whether this person smokes tobacco                                                                                                   | 
| had_illness         | boolean   | "0,1,null"    | Whether this person has been ill in the last two weeks                                                                               | 
| had_malaria         | boolean   | "0,1,null"    | Whether this person has had malaria in the last two weeks                                                                            | 
| had_diarrhoea       | boolean   | "0,1,null"    | Whether this person has had diarrhoea in the last two weeks                                                                          | 
| survey_cluster      | integer   |               | The surveying cluster used for selecting this individual                                                                             | 
| survey_strata       | integer   |               | The surveying strata used for selecting this individual                                                                              | 
| survey_weight       | integer   |               | The surveying weight used for selecting this individual                                                                              | 
| date_sampled        | date      | dd/mm/yyyy    | The date when the sample was taken from the body                                                                                     | 
| sample_type         |  text     |               | "Whether this is a urine, blood, or breastmilk sample"                                                                               | 
| haemoglobin         |  numeric  |               | "The amount of haemoglbin (also known as hemoglobin) in the blood, in grams per litre."                                              | 
| ferritin            |  numeric  |               | "The amount of (serum or plasma) Ferritn found in the blood, in micrograms per litre"                                                | 
| stfr                |  numeric  |               | "The amount of (serum or plasma) Soluble Transferrin Receptors (sTfR) in the blood, in milligrams per litre"                         | 
| rbp                 |  numeric  |               | "The amount of (serum or plasma) Retinol Binding Protein (RBP) in the blood, in micromoles per litre"                                | 
| retinol             |  numeric  |               | "The amount of (serum or plasma) Retinol in the blood, in micromoles per litre"                                                      | 
| rbc_folate          |  numeric  |               | "The amount of red blood cell Folate in the blood, in nanomoles per litre"                                                           | 
| ps_folate           |  numeric  |               | "The amount of serum or plasma Folate in the blood, in nanomoles per litre"                                                          | 
| vitamin_b12         |  numeric  |               | "The amount of (serum or plasma) Vitamin B12 (also known as cobalamin) in the blood, in picomoles per litre"                         | 
| zinc                |  numeric  |               | "The amount of (serum or plasma) zinc, in micrograms per decilitre"                                                                  | 
| crp                 |  numeric  |               | "The amount of (serum or plasma) C-reactive protein (CRP) in the blood, in milligrams per litre. A value >=5 defines inflammation"   | 
| agp                 |  numeric  |               | "The amount of (serum or plasma) Alpha 1 acid GlycoProtein (AGP) in the blood, in grams per litre. A value >=1 defines inflammation" | 
| iodine              |  numeric  |               | "The amount of Urinary Iodine, in micrograms per litre. "                                                                            | 
| time_of_day_sampled | text      |               | "Whether the measurement was taken in the morning or afternoon (pre or post noon local time)"                                        | 
| was_fasting         | boolean   | "0,1,null"    | "Whether the sample was taken while the patient was fasting"                                                                         |

**Comment by rbroth** [comment]
Just editing the comment to indicate the allowed values for education

**Comment by andy-bevan** [comment]
We would also need the metadata about the survey. Details to follow...

**Comment by andy-bevan** [comment]
And details about the household...

**Comment by andy-bevan** [comment]
Thanks @fannymawbey I got the data csv. I may have a few questions...

**Comment by andy-bevan** [comment]
@fannymawbey for the Malawi data we have a dictionary to explain and translate some of the values. Do we have something similar for the Ethiopia data? For example RESIDENCE values are either 1 or 2 in the data, but what does that translate as?

**Comment by fannymawbey** [comment]
right, I'll send that over.

**Comment by andy-bevan** [comment]
@rbroth there are a bunch of boolean columns on the household_member table about the person (is_pregnant, is_smoking, is_ill etc). Then in the biomarker_measurement table there is 'was_fasting'. Just wondering if that should be moved to the hh_member table as it is an attribute of the person, rather than the measurement...?

**Comment by rbroth** [comment]
The original idea from those tables was that one person could have multiple measurements taken and they'd be reported seperately, so you could have your blood taken after fasting the day before, but you could then eat something and have a urine sample taken after lunch. But you're right, it might a good idea. @fannymawbey just to confirm, biomarker measurements data is always given in this "pre-aggregaed" state, where information about a person is collected at the same time that biomarker measurements are taken?

**Comment by andy-bevan** [comment]
The CLUSTER field in the data is arriving as a alphanumeric code but the 'survey_cluster' column in the household_member table is numeric. I guess we need to change the data_type in the column, unless I am missing something?

**Comment by andy-bevan** [comment]
Following today's meeting, we have established that:

- all the data and metadata should be included as a single flat CSV file
- text values and dates should be surrounded by double quotes as a text qualifier
- coded values should be decoded into the actual text value
- boolean values can stay as 1 or 0 or null
- no need to include columns for data which does not exist

**Comment by fannymawbey** [comment]
Great, thanks Andy for noting these. 

Attached Malawi and Ethiopia files. I added the metadata for Malawi in the excel, just let me know if that looks OK. I checked in Notepad and it looks like everything that should be double quoted is but it's not super easy to see in Notepad so please just let me know if something doesn't look right. thank you! I'll send by email as it looks like I can attach csv here.

**Comment by andy-bevan** [comment]
Latest format spec:

|Column Header        |Data Type|Values/Format   |Description                                                                                                                                                                                                   |
|---------------------|---------|----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|person_id            |text     |                |Unique identifier for the person                                                                                                                                                                              |
|sex                  |text     |                |Whether the household member is male or female                                                                                                                                                                |
|education_level      |text     |                |The highest level of education achieved by this person. Can be primary                                                                                                                                        |
|age_in_months        |integer  |                |The age of the person at the time of the survey                                                                                                                                                               |
|is_breastfed         |boolean  |0,1,null        |Whether the child is being breastfed; "true" indicates that they are                                                                                                                                          |
|is_lactating         |boolean  |0,1,null        |Whether this woman is lactating; "true" indicates that she is                                                                                                                                                 |
|is_pregnant          |boolean  |0,1,null        |Whether this woman is pregnant; "true" indicates that she is                                                                                                                                                  |
|is_smoker            |boolean  |0,1,null        |Whether this person smokes tobacco                                                                                                                                                                            |
|had_illness          |boolean  |0,1,null        |Whether this person has been ill in the last two weeks                                                                                                                                                        |
|had_malaria          |boolean  |0,1,null        |Whether this person has had malaria in the last two weeks                                                                                                                                                     |
|had_diarrhoea        |boolean  |0,1,null        |Whether this person has had diarrhoea in the last two weeks                                                                                                                                                   |
|survey_cluster       |text     |                |The surveying cluster used for selecting this individual                                                                                                                                                      |
|survey_strata        |integer  |                |The surveying strata used for selecting this individual                                                                                                                                                       |
|survey_weight        |integer  |                |The surveying weight used for selecting this individual                                                                                                                                                       |
|date_sampled         |date     |dd/mm/yyyy      |The date when the sample was taken from the body                                                                                                                                                              |
|sample_type          | text    |                |Whether this is a urine, blood, or breastmilk sample                                                                                                                                                          |
|haemoglobin          | numeric |                |The amount of haemoglbin (also known as hemoglobin) in the blood, in grams per litre.                                                                                                                         |
|ferritin             | numeric |                |The amount of (serum or plasma) Ferritn found in the blood, in micrograms per litre                                                                                                                           |
|stfr                 | numeric |                |The amount of (serum or plasma) Soluble Transferrin Receptors (sTfR) in the blood, in milligrams per litre                                                                                                    |
|rbp                  | numeric |                |The amount of (serum or plasma) Retinol Binding Protein (RBP) in the blood, in micromoles per litre                                                                                                           |
|retinol              | numeric |                |The amount of (serum or plasma) Retinol in the blood, in micromoles per litre                                                                                                                                 |
|rbc_folate           | numeric |                |The amount of red blood cell Folate in the blood, in nanomoles per litre                                                                                                                                      |
|ps_folate            | numeric |                |The amount of serum or plasma Folate in the blood, in nanomoles per litre                                                                                                                                     |
|vitamin_b12          | numeric |                |The amount of (serum or plasma) Vitamin B12 (also known as cobalamin) in the blood, in picomoles per litre                                                                                                    |
|zinc                 | numeric |                |The amount of (serum or plasma) zinc, in micrograms per decilitre                                                                                                                                             |
|crp                  | numeric |                |The amount of (serum or plasma) C-reactive protein (CRP) in the blood, in milligrams per litre. A value >=5 defines inflammation                                                                              |
|agp                  | numeric |                |The amount of (serum or plasma) Alpha 1 acid GlycoProtein (AGP) in the blood, in grams per litre. A value >=1 defines inflammation                                                                            |
|iodine               | numeric |                |The amount of Urinary Iodine, in micrograms per litre.                                                                                                                                                        |
|time_of_day_sampled  |text     |                |Whether the measurement was taken in the morning or afternoon (pre or post noon local time)                                                                                                                   |
|was_fasting          |boolean  |0,1,null        |Whether the sample was taken while the patient was fasting                                                                                                                                                    |
|Household Details    |         |                |Note that household values must be identical per household id                                                                                                                                                 |
|household_id         |text     |                |Value to uniquely identify the household                                                                                                                                                                      |
|urbanity             |text     |urban,rural,null|Whether this household is located in an urban or rural area                                                                                                                                                   |
|household_expenditure|numeric  |                |How much money this household spends per month in local currency                                                                                                                                              |
|wealth_quintile      |integer  |1,2,3,4,5       |In what quintile of househol wealth this household is (5=richest, 1=poorest). If values are not identical for a given id then use the lowest value in all rows for that household id                          |
|altitude_in_metres   |numeric  |                |The altitude of the household above sealevel in metres. Used to adjust hemoglobin levels when assessing deficiency. If values are not identical for a given id then use the average value per household id    |
|latitude             |numeric  |                |The latitude of the location of the household, or the centroid of the cluster of households this household belongs to. If values are not identical for a given id then use the average value per household id |
|longitude            |numeric  |                |The longitude of the location of the household, or the centroid of the cluster of households this household belongs to. If values are not identical for a given id then use the average value per household id|
|Survey Details       |         |                |                                                                                                                                                                                                              |
|survey name          |text     |                |The name of the survey                                                                                                                                                                                        |
|publication_date     |text     |month year      |The month and year or date when the survey was published                                                                                                                                                      |
|surveying_date_start |text     |month year      |The month and year or date when surveying and interviewing started                                                                                                                                            |
|surveying_date_end   |text     |month year      |The month and year or date when no further interviews took place                                                                                                                                              |
|geometry             |text     |                |The area covered by the survey; all households interviewed by the survey should fall into this area - geometry will be used to represent this area.                                                           |
|geonetwork_uuid      |text     |                |a UUID for Geonetwork. See https://geonetwork-opensource.org/ for further info                                                                                                                                |
|survey_weight_factor |integer  |                |The factor survey weightings have been scaled by                                                                                                                                                              |
|notes                |text     |                |A generic text field for notes about a survey. Can include such as: Whether biomarker measurements were taken from blood plasma or blood serum                                                                |

**Comment by rbroth** [comment]
Make sure to also update the files in the repo

**Comment by andy-bevan** [comment]
Hi @fannymawbey 
One of the new files has a column called 'had_fever'. Is that the same as 'had_illness' or is that a new parameter?

**Comment by andy-bevan** [comment]
The format was updated in a recent MR on the gitlab project so closing this issue.

https://kwvmxgit.ad.nerc.ac.uk/bmgf-maps/data/db-test-data/-/merge_requests/45
