### ISSUE TITLE
Create view for Deficiency R Scripts

### ISSUE THREAD

**Issue by andy-bevan** [micronutrientsupport/database-architecture#143]
Create a view (materialise?) to supply an API call to fetch necessary data to populate R script arguments to calculate deficiency.

**Comment by andy-bevan** [comment]
@rbroth I assume we need this following yesterday's meeting?

**Comment by rbroth** [comment]
Yep, related to #142

**Comment by fannymawbey** [comment]
sorry I don't get this. What do we need @rbroth ?

**Comment by andy-bevan** [comment]
Its what Andy Bean was describing in the meeting yesterday. The R script would expect a list of arguments - one of which would be a dataset of biomarker measurements. Something like:
Survey_id,
country,
biomarker,
group_id,
sample_type,
measurements(biomarker_value),
...

**Comment by fannymawbey** [comment]
ok thanks, that must be the table I just sent to Roman

Le mer. 28 avr. 2021 à 10:32, andy-bevan ***@***.***> a
écrit :

**Comment by spenny-liam** [comment]
Related to #134

**Comment by rbroth** [comment]
Ah, derp, not related to #142 after all
