### ISSUE TITLE
Add allowed value to education level

### ISSUE THREAD

**Issue by andy-bevan** [micronutrientsupport/database-architecture#160]
In the household member table, allow 'university' as an allowed education level

**Comment by rbroth** [comment]
isn't that tertiary?

**Comment by andy-bevan** [comment]
Apparently not. The Ethiopia data includes 3 - tertiary and 4 - university...

**Comment by rbroth** [comment]
@fannymawbey can we reassign "university" as "tertiary education"? I think having both tertiary and university could cause confusion

**Comment by fannymawbey** [comment]
which survey is that?

**Comment by rbroth** [comment]
I've just had a look a the data (exportEthiopia) itself. It looks like there aren't any instances of anyone having education level `4`; just `0`, `1`, and `3`. (A bit suspicious that noone has only secondary education)

**Comment by fannymawbey** [comment]
It's a bit confusing in this dataset as there are so many variables and I have to decide which one works best. Let me send you the dataset with another variable (also education) that seems better constructed

 value                     label
     1                   Primary
     2                 Secondary
     3     Technical/Vocational 
     4 Higher/University/Collage
    88                        DK

**Comment by rbroth** [comment]
I think unifying Technical/Vocational, Higher/University/Collage, and DK as "tertiary" should be fine for our purposes; I rather doubt any of those groups will have micronutrient deficiencies from enough from each other to matter

**Comment by fannymawbey** [comment]
DK is 'don't know' so it should not be anywhere. Not sure what I would do
with technical/vocational

**Comment by rbroth** [comment]
> DK is 'don't know' so it should not be anywhere. 
If it's not too much trouble in the future, unknown or non-applicable values should be coded as `NULL`, that'll be more standardised and make importing slightly easier for us

**Comment by fannymawbey** [comment]
sure. this dataset is a bit messy

**Comment by rbroth** [comment]
@fannymawbey @andy-bevan  Did we agree that 'tertiary' is good enough as a catch-all term?

**Comment by andy-bevan** [comment]
If 'higher' can be translated to 'tertiary' that would negate the need to update the check constraint for the WRA Ethiopia data...

**Comment by andy-bevan** [comment]
The Ethiopia data is now coming through translated with five different values which suggests that we need to accommodate five levels of eductation rather than four, with two of them merged. In the 'dictionary' file the level 4 translates to 'University' rather than 'higher' but as long as we have five values, it should be straightforward for data providers to translate into the appropriate text, as long as we specifiy what they are in the import format specs.

**Comment by rbroth** [comment]
>  it should be straightforward for data providers to translate into the appropriate text, as long as we specifiy what they are 

yes, but that's the question: What's the difference between 'higher', 'university', and 'tertiary'? As far as I'm aware, 'tertiary' covers the former two, and if we're translating values for BYOD we need to know what the values mean. How will an end-user know the difference between 'higher' education and 'tertiary' education for their needs?

@fannymawbey

**Comment by fannymawbey** [comment]
Dear Roman,

I tend to agree with you. We could keep have a 'higher' that includes
university, tertiary (as long as it's higher than secondary)

Would that be ok?

Fanny

**Comment by rbroth** [comment]
What are the definitions of those terms? What does the survey say? I'm not against including a 5th education level, as long as it's better defined than a single word that conflicts with the definition of another education level

**Comment by rbroth** [comment]
Executive decision at meeting today: Just put it in
