### ISSUE TITLE
Update RBC_Folate precision

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#168]
- Ensure that the RBC_Folate column has the correct scale and precision values
- Update import scripts to import the data (V0.3.0.210__biomarker_ethiopia.sql#L1283)

**Comment by rbroth** [comment]
@fannymawbey, looking at the exportEthiopia data, it looks like some extra decimals have snuck in; unless the machines for measuring RBC Folate have a precision of 0.000001 nmol/L? What's the number of decimals given in the original data?

**Comment by fannymawbey** [comment]
oh dear. one decimal to the right should be enough (example: 348.9)

**Comment by fannymawbey** [comment]
same with sfolate - 2 decimals to the right should be enough

BMI - one to the right

ZincICPMS - one to the right

**Comment by rbroth** [comment]
https://github.com/micronutrientsupport/database-architecture/pull/169
