### ISSUE TITLE
Survey Dates - Month Only?

### ISSUE THREAD

**Issue by andy-bevan** [micronutrientsupport/database-architecture#173]
Can we store survey dates i.e. dates related to the survey as month and year only? That is how they are arriving in the data and we have a steer from Fanny that its as much precision as is required.

Related to issue #142

**Comment by andy-bevan** [comment]
Looks like the resolution of date data type is 1 day so it won't accept month/year. 

Gives us a choice:

 - change the data type to text
 - add default 01 to the submitted date on import
@rbroth

**Comment by rbroth** [comment]
I'd prefer the latter. What will the data be used for? If we're just using it when we regurgitate a whole bunch of unstructured survey metadata then text might useful. If we're actually going to run calculations (e.g. this person was this many months old at the time of the survey, therefore they are this old today) then definitively default to first day of month.

**Comment by andy-bevan** [comment]
> I'd prefer the latter. What will the data be used for? If we're just using it when we regurgitate a whole bunch of unstructured survey metadata then text might useful. If we're actually going to run calculations (e.g. this person was this many months old at the time of the survey, therefore they are this old today) then definitively default to first day of month.

We can use the interview date for that.

**Comment by rbroth** [comment]
Then text
