### ISSUE TITLE
Define standard input format for food consumption

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#175]
Split off from #77 

How similar is the consumption data for 
- individuals
- households
- countries

### The various Consumption Tables
- food_genus_id
- original_food_name
- food_genus_confidence
- date_consumed
- amount_consumed_in_g

**Comment by LuciaSegovia** [comment]
Some questions here:

 - date_consumed --> Is it referring to the recall period (i.e., one day, 7-days, per year,...) or is the actual date when data was recorded/ collected (i.e., 05/07/2021)?

 - amount_consumed_in_g --> Is this per day or in per recall period?

I suggest to add:
 
- orginal_food_id

**Comment by spenny-liam** [comment]
> Some questions here:
> 
> * date_consumed --> Is it referring to the recall period (i.e., one day, 7-days, per year,...) or is the actual date when data was recorded/ collected (i.e., 05/07/2021)?
> * amount_consumed_in_g --> Is this per day or in per recall period?
> 
> I suggest to add:
> 
> * orginal_food_id

@LuciaSegovia Are you free to zoom with us to decide on all this today?

**Comment by rbroth** [comment]
The relevant database tables, which have comments for the columns (but which we'll change as we get more specific):
- https://github.com/micronutrientsupport/database-architecture/blob/develop/db/objects/V0.1.0.750__Country_Consumption.sql
- https://github.com/micronutrientsupport/database-architecture/blob/develop/db/objects/V0.1.0.700__Household_Consumption.sql
- https://github.com/micronutrientsupport/database-architecture/blob/develop/db/objects/V0.1.0.800__household_member_consumption.sql

**Comment by LuciaSegovia** [comment]
> @LuciaSegovia Are you free to zoom with us to decide on all this today?

Sure! Do you want me to create a zoom meeting now? @spenny-liam

**Comment by spenny-liam** [comment]
> > @LuciaSegovia Are you free to zoom with us to decide on all this today?
> 
> Sure! Do you want me to create a zoom meeting now? @spenny-liam

Yeah sure lets do it

**Comment by LuciaSegovia** [comment]
Sorry @spenny-liam, I forgot to ask, the country_id variable is ISO2 or ISO3?

**Comment by spenny-liam** [comment]
> Sorry @spenny-liam, I forgot to ask, the country_id variable is ISO2 or ISO3?

ISO 3166 2 letter codes please.

**Comment by LuciaSegovia** [comment]
I uploaded the data into Teams. A small note, FBSH corresponds to the 'old Food Balance Sheet' (http://www.fao.org/faostat/en/#data/FBSH) and FBS corresponds to the "new Food Balance Sheet" (http://www.fao.org/faostat/en/#data/FBS).

**Comment by spenny-liam** [comment]
> I uploaded the data into Teams. A small note, FBSH corresponds to the 'old Food Balance Sheet' (http://www.fao.org/faostat/en/#data/FBSH) and FBS corresponds to the "new Food Balance Sheet" (http://www.fao.org/faostat/en/#data/FBS).

That's great thank you

**Comment by spenny-liam** [comment]
Hi @LuciaSegovia Sorry how much of a pain would it be for you to switch to the 3 letter country codes? I was going to do it myself but its taking me hours

**Comment by LuciaSegovia** [comment]
@spenny-liam sorry for the late reply. I can do it right now it you still need it :)

**Comment by spenny-liam** [comment]
Yes please sorry my mistake with asking for the wrong country codes

**Comment by LuciaSegovia** [comment]
No worries! It took me 3sec to change it :) It's on Teams now
