### ISSUE TITLE
Create View for Nutrient Deficiencies by country and admin division

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#18]
For the MVP, to test the functionality, we want a view that Shows:

the nutrient deficiencies (i.e. how much of a given micronturient a person/household is consuming vs the recommended daily/weekly allowance)
of populations (i.e. household or household members
on an administrative level (i.e. sub-country)

**Comment by rbroth** [comment]
The area could be a spatial input

**Comment by rbroth** [comment]
How do we want aggregation of consumption to work? How do we mix individual and household level data?

**Comment by rbroth** [comment]
Ignore this, scope too big. Focus on the other, smaller tables first

**Comment by bgsandan** [comment]
This is covered by `household_deficiency_afe_aggregation` and `country_deficiency_afe` views
