### ISSUE TITLE
Remove nonsense data

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#193]
V0.2.0.440__survey.sql only contains nonsense survey data and can be safely removed, since we now have several real datasets to work with. We should also have a look at other bits of data and dictionary entries to make sure that they are real data and in the proper repo/folder

**Comment by rbroth** [comment]
I'm removing `V0.3.0.20__gambia-data.sql` and looking at also removing `V0.3.0.10__malawi-data.sql`, but that adds some things into the `food_group` and `citation` tables, and I'm not sure if the python scripts add those things.

**Comment by andy-bevan** [comment]
> I'm removing `V0.3.0.20__gambia-data.sql` and looking at also removing `V0.3.0.10__malawi-data.sql`, but that adds some things into the `food_group` and `citation` tables, and I'm not sure if the python scripts add those things.

@spenny-liam 's python script does insert into those two tables but I'm not sure if there is any Malawi data in the files that are imported?

**Comment by rbroth** [comment]
The malawi FCT is called MAFOODS. If the python script takes care of those things I'll go ahead and delete the file

**Comment by rbroth** [comment]
I've just tried it; removing `V0.3.0.10__malawi-data.sql` results in no data being inserted into the `citation` table. Leaving it in results in duplicate rows in the fooditem table

**Comment by andy-bevan** [comment]
> I've just tried it; removing `V0.3.0.10__malawi-data.sql` results in no data being inserted into the `citation` table. Leaving it in results in duplicate rows in the fooditem table

I just tried removing it. and two other 'test' data files. No data in Citation table - with or without this file. Fooditem table now has one less record - which is the 'test' record.

**Comment by andy-bevan** [comment]
Files removed and change merged.
