### ISSUE TITLE
Definition of ash_in_g

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#198]
We don't currently have a comment for fooditem.Ash_in_g. 

Previously it was suggested that we use "Ash content of this food item, in grams per 100g;" ([source](https://github.com/micronutrientsupport/database-architecture/issues/1#issuecomment-703576975)). However, seeing as most foods that humans eat don't contain appreciable amounts of ash (no jokes about my cooking!), It think a better explanation of this might be "the amount of ash leftover when 100 grams of this food item are burnt in a food-ashifying-device" or something along those lines.

@LuciaSegovia, how is this ash value derived?

**Comment by LuciaSegovia** [comment]
As much as I would love to use the definition that you proposed, I think that it is more accurate to say something like "ash content per 100g of edible portion". We can include a more extensive explanation if you want: "ash values in g are used to estimate available carbohydrates and the sum of proximates. The total amoung in g should be aproximate igual to the sum of individual minerals (transformed from mg to g)"
