### ISSUE TITLE
How to report food composition to end users

### ISSUE THREAD

**Issue by LuciaSegovia** [micronutrientsupport/database-architecture#210]
We need to provide some information about what food composition data is used and how data gaps in food composition tables are filled up in the tool. 

The *ideal* is to report what is the original source for each nutrient-food item combination. I have attempted to do it in two ways:

1) Adding a extra-column per nutrient with the reference in the food composition table: For exmple, selenium_in_mcg, selenium.ref. However, I believe that it become a bit messy when you have multiples dataset interating to each other.

2) Creating a *parallel* food composition table: For example, for the regional food composition tables, I created a separated food composition table identical but with the reference of each nutrient - food item combination. 

region | food_item | energy | carbohydrates_available | protein | fat | fibre | phytate | ca | cu | fe | i | mg | se | zn
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
E | Apples | Apples, raw, with skin_d | Apples, raw, with skin_d | Apples, raw, with skin_d | Apples, raw, with skin_d | Apples, raw, with skin_d | Apples, raw, with skin_d | Apples, raw, with skin_d | Apples, raw, with skin_d | Apples, raw, with skin_d | Apples, eating, average, raw_g | Apples, raw, with skin_d | Apples, raw, with skin_e | Apples, raw, with skin_d
E | Aquatic Animals, Others | Fish, fresh_d | Fish, fresh_d | Fish, fresh_d | Fish, fresh_d | Fish, fresh_d | Fish, fresh_d | Fish, fresh_d | Fish, fresh_d | Fish, fresh_d | Mackerel, spanish, raw_f | Fish, fresh_d | Matemba (fresh)_c | Fish, fresh_d
E | Aquatic Plants | Seaweed, agar, raw_e | Seaweed, agar, raw_e | Seaweed, agar, raw_e | Seaweed, agar, raw_e | Seaweed, agar, raw_e | x_x | Seaweed, agar, raw_e | Seaweed, agar, raw_e | Seaweed, agar, raw_e | Seaweed, nori, dried, raw_g | Seaweed, agar, raw_e | Seaweed, agar, raw_e | Seaweed, agar, raw_e
E | Bananas | Banana, ripe_d | Banana, ripe_d | Banana, ripe_d | Banana, ripe_d | Banana, ripe_d | Banana, ripe_d | Banana, ripe_d | Banana, ripe_d | Banana, ripe_d | Banana, fruit, raw_f | Banana, ripe_d | Banana_c | Banana, ripe_d

In my opinion, the second solution is quite practical, since it allows to only those users that are interested in that info to download it as part of the metadata. However, I don't know how demanding it would be for the tool :)

This is the second *issue* that we discussed on Friday :) @bgsandan, @spenny-liam, @Gare94, @LouiseAnder  Feel free to comment or add anything that I missed!

**Comment by LouiseAnder** [comment]
thank you @LuciaSegovia  this is a good point.

I think there may be a simple short term answer which is that the user at the moment is looking at one nutrient at a time. Are we thinking of the methods and metadata links out from, say, QuickMAPS?

If so, I think that either approach works without getting too messy, but...  

When we can enable a more 'dashboard' overview/summary, I think I prefer your second option, which creates a FCmetaT, as this would be incredibly easy to find the item/nutrient information you are after as a user.

**Comment by LuciaSegovia** [comment]
> I think there may be a simple short term answer which is that the user at the moment is looking at one nutrient at a time. Are we thinking of the methods and metadata links out from, say, QuickMAPS?

I was thinking that, so all the information will be as a download file or something like that. However, as you mentioned that users will be looking at one nutrient at a time, I am thinking that if they are looking at different scenarios (i.e., increasing fish consumption or changing white to orange sweet potato) they might be interested to know the actual FCT source, what do you think? But, maybe, it's just me that I am really into the FCTs world 😂

**Comment by LouiseAnder** [comment]
> 
> 
> > I think there may be a simple short term answer which is that the user at the moment is looking at one nutrient at a time. Are we thinking of the methods and metadata links out from, say, QuickMAPS?
> 
> I was thinking that, so all the information will be as a download file or something like that. However, as you mentioned that users will be looking at one nutrient at a time, I am thinking that if they are looking at different scenarios (i.e., increasing fish consumption or changing white to orange sweet potato) they might be interested to know the actual FCT source, what do you think? But, maybe, it's just me that I am really into the FCTs world 😂

ooooooh, yes, _after_ QuickMAPS you are correct, things are different. So the tool will display the 'current' composition of the item being altered and the relative/absolute different composition of the item(s) being altered. So, downloading the FCmetaT would give the starting FCT information (as QuickMAPS) but not the adjusted.

I *think* that's okay as the interface and any downloads will really clearly indicate the  input and user-generated values, but if you think that's not going to be enough really happy to think through further. 

_EVERYONE_ should love an FCT / FCmetaT.....

**Comment by LuciaSegovia** [comment]
> I _think_ that's okay as the interface and any downloads will really clearly indicate the input and user-generated values, but if you think that's not going to be enough really happy to think through further.

Agree, I think it's ok, as long as it is communicated clearly that it is the original FCT. Would users be allowed to download the FCT data used in the tool? 


> _EVERYONE_ should love an FCT / FCmetaT.....

👏 👏 👏

**Comment by LouiseAnder** [comment]
> 
> Agree, I think it's ok, as long as it is communicated clearly that it is the original FCT. Would users be allowed to download the FCT data used in the tool?
> 

Yes, as long as none of the input data are confidential in any way?  And the output is a 'MAPS generated' dataset bespoke to the country + MN, because no FCT has all of the data for all of the items.

**Comment by bgsandan** [comment]
Closing for now
