### ISSUE TITLE
Information about food matching

### ISSUE THREAD

**Issue by LuciaSegovia** [micronutrientsupport/database-architecture#211]
There are a number of questions regarding what information are we reporting in relation to food composition and food matching. 

1) How are we reporting the `NA` values? For example, are we reporting percentage of missing value per food item or per nutrient? Do we want to set a maxium number of missing values? For example, if the number of missing values for iodine is higher than 70% of the total, we will not report that micronutrient content in the diet. 

2) How are we reporting the location of the final data? For example, if there is one country that has very limited food composition data and most of the values are coming from a diffferent countries food composition tables. How are we reporting that? Should we report the percentage of data coming from different locations? 

Please, @bgsandan, @spenny-liam, @Gare94 and @LouiseAnder , feel free to comment on this :) This is the thrid and last *issue* raised on Friday

**Comment by LouiseAnder** [comment]
To what extent will we end up with NA values, do we have any feel for that?

Also, on what basis would we issue a flag? If 70% of iodine values were missing (which is a good example) but you still had marine fish, other marine produce and iodised salt data it _probably_ doesn't matter that 70% are missing....?  Are you thinking a list that the user could inspect of just the items or is this also reporting quantity consumed?

I think that maybe 1 could be reported alongside 2. 

For 2 I think it would be good to prioritise what would be more useable/useful - is it the full list of items or is it the e.g. top 20 items (as in the tree diagrams) contributing to MN supply? Again, it could be that all the spices and confectionery items (with a large 'n') reported are manufactured far far away, but they are not contributing to the top XX items for that MN. This would presumably not be of much concern to the user?

What might be of more concern is if all top 20 items for, e.g. Se in a SSA nation were coming from N Am FCTs, where we know Se to be typically elevated. Realise that's an extreme example. 

does this help?

thank you :)

**Comment by LuciaSegovia** [comment]
> To what extent will we end up with NA values, do we have any feel for that?

For the datasets that are currently in the tool, I think numbers will be very low. But I was thinking for the future :)



> Also, on what basis would we issue a flag? If 70% of iodine values were missing (which is a good example) but you still had marine fish, other marine produce and iodised salt data it _probably_ doesn't matter that 70% are missing....? Are you thinking a list that the user could inspect of just the items or is this also reporting quantity consumed?

Yes! Totally agree, I was thinking percentage of consumed items (I didn't express it properly, sorry!). But, I guess it will be difficult to flag it, since it would depend on the nutrient that we are looking at, as you mentioned. I guess then (being pragmatic again) that % of missing values of the total nutrient consumption is good enough. 



> For 2 I think it would be good to prioritise what would be more useable/useful - is it the full list of items or is it the e.g. top 20 items (as in the tree diagrams) contributing to MN supply? Again, it could be that all the spices and confectionery items (with a large 'n') reported are manufactured far far away, but they are not contributing to the top XX items for that MN. This would presumably not be of much concern to the user?

I was thinking we can do a simple *pie chart* with the % of data coming from the different countries for overall reporting of location. Then, maybe we could add an extra layer of complexity by reporting the location for the top-20 itmes. Although, in line with your thoughts, it might not be relevant for all micronutrients, since it will not make as big of a difference for most of the vitamins. 

> does this help?

Always :)

**Comment by LouiseAnder** [comment]
> 
> I was thinking we can do a simple _pie chart_ with the % of data coming from the different countries for overall reporting of location. Then, maybe we could add an extra layer of complexity by reporting the location for the top-20 itmes. Although, in line with your thoughts, it might not be relevant for all micronutrients, since it will not make as big of a difference for most of the vitamins.
> 
Yes, something visual is good for the user (NB Katie and Paulius thinking in this way for cost data steps too, so the 'front end' capability for graphics is going to be planned in).  We talked about bar charts (stacked or adjacent) as well as pie charts, as pie charts are considered notoriously difficult for users to understand, although lots of users may think they prefer them (apparently).

**Comment by LuciaSegovia** [comment]
True, I had the notion that pie charts were "bad" as well, but appartently there is a new wave claiming them back. I am very happy to explore way of visualizing food compo. I'm sure you know it but [here's](https://datavizproject.com/) a great resoure for data visualization, radial bar chart are quite nice too!

**Comment by bgsandan** [comment]
Covered by the matching statistics in the fron-end
