### ISSUE TITLE
Add name column for non-English admin area names

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#212]
Adminsitrative areas and countries currently only have their english name stored. We want to store both the English name (as defined by the UN officaial name list of countries ) in their short and long versions, as well as the proper name of the country/admin area in their native language and script.

Example: 
| ISO code | short english | long english | native |
| -           | -------------| ------------- | ---- |
| GER      | Germany    | Federal republic of Germany | Bundesrepublik Deutschland |

**Comment by bgsandan** [comment]
For pragmatism, currently using "geography" as a non-political, non-geographic term across the board
