### ISSUE TITLE
top20_mn_per_hhsurvey view doesn't include fct_source_id 1

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#218]

**Comment by andy-bevan** [comment]
The food_genus_id in the fooditem table where the fct_source_id = 1 does not seem to have corresponding values in the household_consumption table.

**Comment by andy-bevan** [comment]
I think this means the Malawi food consumption data is missing...?

**Comment by andy-bevan** [comment]
There doesn't even seem to be any Malawi records in the fooditem table now. I.e. there are no records where fct_source_id = 1.

**Comment by andy-bevan** [comment]
MAFOODS is the Malawi data. The data refers to the fct_source_id of 21 so do we even need fct_source 1 Malawi?
