### ISSUE TITLE
Create New 'Source File' Entity 

### ISSUE THREAD

**Issue by andy-bevan** [micronutrientsupport/database-architecture#222]
We are starting to collect metadata about data files submitted for loading into the database. We need a home for this metadata if we are to store it. Example:

> 1 value of plasma zinc was considered biologically implausible and was excluded from the analysis (ref: IZINC technical brief. Adjusting plasma or serum zinc concentrations for inflammation. 2020)

Our initial idea, at least for biomarker measurement data was to roll the metadata into the 'notes' column in the 'survey' entity. However, not all notes included in a file would be relevant for the whole survey or other files submitted.

This issue proposes that we create a new entity called 'data_file' or perhaps 'source_file' which would store metadata about any data files submitted for loading, not just biomarker measurements.

Any data loaded could then be linked back to a source file which would allow a record of provenance. The use-case for this might be:

>"I am a scientist using the MAPS_BMGF website for research and I want to know the reasons why some data was excluded from the survey results so that I have an explanation for a missing datum."

Columns might include:

- file_id (auto-generated)
- file_name
- created_by
- created_date
- notes (might include notes about which data were excluded from the file, and why)

We would need to expand the data import format to include these extra columns, and existing files would need to be updated to include this metadata.

**Comment by andy-bevan** [comment]
@rbroth @fannymawbey @bgsandan @LouiseAnder @spenny-liam @dzvoti 

Alerting you all to the issue discussed in this morning's stand-up meeting. Please feel free to comment/agree/disagree before we implement.

**Comment by LouiseAnder** [comment]
Agree, the use case puts it very nicely. Thanks @andy-bevan !
