### ISSUE TITLE
interview_date not populated in household table

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#224]
The `interview_date` field is not populated for the current household consumption survey data in the `household` table.  This means the `monthly_food` materialized view doesn't work

**Comment by andy-bevan** [comment]
The interview_date column insert is commented out in this file: V0.3.0.300__ihs4_households.sql

**Comment by andy-bevan** [comment]
@rbroth this script is not inserting the interview date:
>V0.3.0.200__biomarker_malawi_women.sql

but can we delete it now that we are importing directly from the source file?
>e.g. exportMalawiWRA.csv

**Comment by andy-bevan** [comment]
In issue #172 we decided that the interview date was better placed in the household_member table rather than the household table. Looks like we need to update the view to match.

**Comment by bgsandan** [comment]
Good detective work! 🙂

**Comment by rbroth** [comment]
> 
> 
> @rbroth this script is not inserting the interview date:
> 
> > V0.3.0.200__biomarker_malawi_women.sql
> 
> but can we delete it now that we are importing directly from the source file?
> 
> > e.g. exportMalawiWRA.csv

Does the python script have the same output as the .sql file? If so, yes, but double check that everything actually is the same. E.g. the sql script inserts data into the survey group definition, I don't know if the python script does the same

**Comment by andy-bevan** [comment]
Yes, it does. 👍

**Comment by andy-bevan** [comment]
The view seems to be working now. @bgsandan can you confirm and close the issue?
