### ISSUE TITLE
Get a list of micronutrients

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#23]

**Comment by rbroth** [comment]
I'm second-guessing my architecture choice now. Currently, micronutrients are implicitly defined in the column headers of the fooditem table. We do have an intake_thresholds table that lists the micronutrients as rows, but I think these need to be unified somehow

**Comment by rbroth** [comment]
#40

**Comment by bgsandan** [comment]
Table `micronutrients` can be queried to get the list by the API.  Closing this DB issue
