### ISSUE TITLE
Should food_genus table have food_group_ids?

### ISSUE THREAD

**Issue by andy-bevan** [micronutrientsupport/database-architecture#237]
Currently the only rows populated with a food_group_id are the apparent 'test' rows with ids such as 'Andy1', 'Andy2' etc.

The 'real' food genus rows have null food_group_ids.

**Comment by andy-bevan** [comment]
@LouiseAnder @bgsandan 
I am wondering if this might be at the heart of the issue?

**Comment by LuciaSegovia** [comment]
Hi @andy-bevan, in all fct there are food_groups and food_subgroups (names), I also have food_group_ids in my dataset, do you want me to change it? Or will that not solve the problem?

**Comment by andy-bevan** [comment]
Hi @LuciaSegovia , don't change anything for now, until we have checked where this information should come from. 
At the moment the table is populated from two hard-coded scripts, one of which is obviously dummy/test data. The other looks real but lacks the food_group_id. 
@rbroth, do you know where the data comes from in this script: V0.3.0.280__food_genus.sql?

**Comment by LuciaSegovia** [comment]
@andy-bevan if you want I can send you the "master" file with all food_genus_id, food_group_id, etc. and their corresponging food_genus_name, food_group_name, etc.

**Comment by rbroth** [comment]
> @rbroth, do you know where the data comes from in this script: V0.3.0.280__food_genus.sql?

Email from Lucia on Thu 2021-07-08 12:40

**Comment by andy-bevan** [comment]
> @andy-bevan if you want I can send you the "master" file with all food_genus_id, food_group_id, etc. and their corresponging food_genus_name, food_group_name, etc.

Yes that sounds like what we need. No rush for today though, as I am about to finish for the weekend. Thanks for your help this week 😄

**Comment by LuciaSegovia** [comment]
@rbroth I put it on Teams ([here](https://nercacuk.sharepoint.com/:x:/r/sites/BGSBMGFMAPS/Shared%20Documents/WP2%20-%20Data%20curation/Food%20Composition%20Tables/MAPS_Dictionary_master-file_v2.6.csv?d=w4ea316c7f13649efb6ded2447ea9a839&csf=1&web=1&e=Vqe7Vn)) forgot to mention it here, my bad!

**Comment by andy-bevan** [comment]
@rbroth before I pick up this issue, is it something you are already looking at as part of your work on issue #283 ?

**Comment by rbroth** [comment]
I'm not looking at this particular bit, but I'm not sure if food group IDs are getting autopopulated by the python scripts. Feel free to have a go, it hopefully shouldn't step on my toes

**Comment by andy-bevan** [comment]
First thing to note is that the test data mentioned above has been removed by an earlier merge request on db-test-data. (MR!41)

**Comment by andy-bevan** [comment]
Latest build of the database shows that all rows in food_genus table now have food_group_id populated.
