### ISSUE TITLE
RefreshallMaterializedViews function not working in deployment CI

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#252]
The RefreshallMaterializedViews function should be called at the end of python data import CI pipeline.  It doesn't appear to be being executed (based on the logs) or if it is it isn't working and the materialized views aren't updated when the database is rebuilt/populated.

Current workaround: 

1.  Connect to db
2.  Run `set search_path=bmgf,public; select bmgf.refreshallmaterializedviews('bmgf');`

**Comment by rbroth** [comment]
#269
