### ISSUE TITLE
Loaded data issues

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#268]
There are a few issues/missing values with the current set of data being loaded into the tool by the data pipeline.

Currently I am 'addressing' them with a manually run 'monkey-patch' SQL (snippets below) but they need to be addressed correctly and less flakily as part of the pipeline:

1.  The ISH4 Malawi household survey does not contain a geometry in the `survey` table, which means the data is not selected by the various views and materialized views.  Monkey-patch SQL copies geometry from another row, but this should be improved

```sql
-- Ensure malawi househols consumption survey has a geometry
with mwi as (select geometry from survey where id = 2)
update survey set geometry = mwi.geometry from mwi where survey.id=1;
```

2\. The `household_member` table doesn't have the group\_id field populated for MEN, PSC or SAC (only WRA is populated).  This stops the survey data appearing in the biomarker\_summary view

```sql
-- Set group id in household_member table for Pre-School Children
with psc_ids as (
	select hm.id from biomarker_measurement bm
	join household_member hm ON hm.id = bm.household_member_id
	where hm.original_id like 'PSC%'
)
update household_member 
set group_id = 'PSC'
from psc_ids
where household_member.id = psc_ids.id;

-- Set group id in household_member table for Men
with men_ids as (
	select hm.id from biomarker_measurement bm
	join household_member hm ON hm.id = bm.household_member_id
	where hm.original_id like 'M%'
)
update household_member 
set group_id = 'MEN'
from men_ids
where household_member.id = men_ids.id;

-- Set group id in household_member table for School-age Children
with sac_ids as (
	select hm.id from biomarker_measurement bm
	join household_member hm ON hm.id = bm.household_member_id
	where hm.original_id like 'SAC%'
)
update household_member 
set group_id = 'SAC'
from sac_ids
where household_member.id = sac_ids.id;
```

3\. The call to the `refreshallmaterializedviews` function doesn't work as part of the python pipeline (mat views don't update and there is no console indication of anything happening).  When executed directly on the DB it works

```sql
-- Actually update materialized views
select bmgf.refreshallmaterializedviews('bmgf');
```

**Comment by andy-bevan** [comment]
First issue solve by including geometry from the country table in the initial survey record insert... committed to branch 268

**Comment by andy-bevan** [comment]
The second issue - if the group_id is included in the source file, then it will make its way into the database, as it is.

**Comment by rbroth** [comment]
Working Point 3 in issue #269

**Comment by andy-bevan** [comment]
I will submit a merge request to address the first two issues in the db-test-data project.

**Comment by andy-bevan** [comment]
Merged.
