### ISSUE TITLE
Food items not matching to food composition data

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#283]
Food consumption data for Nigeria is not matching to food composition data (see screenshot below). 

![GetAttachmentThumbnail](https://user-images.githubusercontent.com/37301590/150999439-9fc6a1db-ff43-4ecb-8100-3ff98675426c.png)

**Comment by rbroth** [comment]
@bgsandan Do you know which particular views are used for this part of the API?

**Comment by bgsandan** [comment]
Map data from country_deficiency_afe_aggregation

Match statistics come from country_unmatched_totals
________________________________

**Comment by bgsandan** [comment]
Treemap from
top20_mn_per_country

________________________________

**Comment by bgsandan** [comment]
https://github.com/micronutrientsupport/api/tree/develop/src/models contains the models used by the API. Each model includes DB view info at the top of the file
________________________________

**Comment by rbroth** [comment]
Short-term workaround: disable food composition datasets until the percentage is at a proper percentage, then work on actually fixing the bug

**Comment by rbroth** [comment]
@LouiseAnder

**Comment by bgsandan** [comment]
Have temporarily removed:

*   KEN\_FCT
*   LSO\_FCT
*   WAFACT
*   uFish
*   uPulses

Pushing through the pipelines and will see if this improves things

**Comment by LouiseAnder** [comment]
Thank you! Has updated on front end - now though the % match also not showing for e.g. Nigeria (as prev observed e.g. Lesotho).

**Comment by rbroth** [comment]
I'm playing around with deleting various csvs and I can confirm that deleting som FCTs leads to no matched and therefore no data

**Comment by bgsandan** [comment]
Looking into that now.  Hopeful situation is that that means 100% match.  Less hopeful situation is something wrong with the matching statistics.  Will update when more clear

**Comment by bgsandan** [comment]
Certainly, re-running the example from the screenshot at the top of this issue now shows a more diverse range of food items and a higher availability of calcium than with the previous FCT selection

![](https://user-images.githubusercontent.com/39411049/151525079-89324daa-a6ac-4fe9-b915-7629750b453e.png)

**Comment by rbroth** [comment]
Discussion results: 
- @bgsandan to remove the FCT CSVs to make the nigeria data work, then close this issue.
- It might be worth to move a lot of the food composition to consumption matching into functions and imperative logic in order to make it easier to reason about; we have a lot of intermediate views that serve essentially only to store intermediate calculation results. @rbroth to open new issue for this, as the food matching algorithm still needs to be fixed

**Comment by LouiseAnder** [comment]
Noting the above that Nigeria is an example, not the only manifestation, of the local FCT needing cascade functionality to create a 'complete' estimate of nutrient availability and that the regional FCTs provide this data coverage.

**Comment by rbroth** [comment]
@andy-bevan and I have worked on this and created a function that should fix the food consumption to composition matching. Our todo now:

- [ ] streamline the function(s)
	- [ ] drop/clean up intermediate tables
- [ ] create the results table separately
- [ ] have it as a function
- [ ] integrate the function into the rest of the system
- [ ] remove the code that deletes the extra FCTs

**Comment by rbroth** [comment]
- [ ] Report number of unmatched items
- [ ] report weight of unmatched consumption items

**Comment by rbroth** [comment]
- [ ] do country-level matching

**Comment by rbroth** [comment]
This may have been fixed, according to @bgsandan
