### ISSUE TITLE
household_deficiency_afe_aggregation not updated in refreshAllMaterializedViews call

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#293]
*   After CI execution the view is empty:

![](https://user-images.githubusercontent.com/39411049/151195267-d0599f72-66ed-41d4-a5e2-2989d9df6a3d.png)

*   When explicitly calling refreshAllMaterializedViews function the view is not updated (the other 9 are):

![](https://user-images.githubusercontent.com/39411049/151196101-f2367e3a-0a21-48fd-b497-37822805cb79.png)

*   Explicitly refreshing the view works:

![](https://user-images.githubusercontent.com/39411049/151196460-0313d68d-0ead-4125-88f2-ce7a3429e3fe.png)

![](https://user-images.githubusercontent.com/39411049/151198217-cf40a95e-d8c5-4a40-81c9-ed5a298e4dc9.png)

**Comment by bgsandan** [comment]
cc: @rbroth - weird behaviour here!

**Comment by rbroth** [comment]
Is the view created in teh correct schema? I've had problems of db objects accidentally being created in the public schema

**Comment by bgsandan** [comment]
Yup, top screenshot is the view of all materialized views in the bmgf schema

**Comment by bgsandan** [comment]
This line is the culprit https://github.com/micronutrientsupport/database-architecture/blob/346dde7aa1a3e4f48cc2394bacdc567847384f25/db/objects/R__105__RefreshAllMaterializedViews.sql#L15 🤦
