### ISSUE TITLE
Food groups are shown twice

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#295]
In this instance, 'Vegetables, other...' versus 'vegetables, other....'. Porbably to do with capitalisation

https://preview.micronutrient.support/quick-maps/diet/baseline?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WR

![GetAttachmentThumbnail](https://user-images.githubusercontent.com/37301590/151338791-c15bf473-5614-42d1-8427-55eb486c753f.png)
A

**Comment by andy-bevan** [comment]
Does anyone know if these would count as duplicates?

Cereals
Cereals and their products
Cereals, other and products

@bgsandan @rbroth @LuciaSegovia

**Comment by andy-bevan** [comment]
Also:

Eggs and products
Eggs and their products

**Comment by LuciaSegovia** [comment]
@andy-bevan, are those food_groups? or food_names?

**Comment by andy-bevan** [comment]
These are food groups.

**Comment by LuciaSegovia** [comment]
> These are food groups.

I think I know where the duplication is coming from. It is from an old version of a FCT that we generated to match the Household Survey data in Malawi (IHS4). I was used before we agreed on the composition matching hierarchy. It's this one in [here](https://nercacuk.sharepoint.com/:x:/r/sites/BGSBMGFMAPS/Shared%20Documents/WP2%20-%20Data%20curation/Food%20Composition%20Tables/ihs4-fct-v0.1.csv?d=wd0ded779465e48e59d22040d824e2440&csf=1&web=1&e=FeLp0C) I hope it helps :)

**Comment by rbroth** [comment]
>  FCT that we generated to match the Household Survey data in Malawi (IHS4)

Can we get rid of that one?

**Comment by LuciaSegovia** [comment]
@rbroth I think we should, it may cause some missing values, if the FCT cascade is not fully implemented. But I think it would be good to remove it :)

**Comment by andy-bevan** [comment]
The file mentioned above does not seem to be used directly by any of the loading processes.
The food groups are loaded like:

1. Hard coded values inserted when the food group table is created
 - these are depended on by impact commodities - if the food groups are missing an error occurs when the impact commodities are loaded.
 2. Food groups are loaded from the food composition tables during the python loading process. E.g. MAPS_MAFOODS_v1.5.csv. the script checks for existing values and uses those rather than adding duplicates

So if the initial hard codes inserts are differently worded duplicates of the food groups arriving in the CSV files, if they are updated to match then the duplicates would not occur. 

@LuciaSegovia does this make sense?

**Comment by andy-bevan** [comment]
Initial hardcoded values:

 (0,0,'other')
    , (1,1, 'Cereals,wheat and products')
    , (101,1,'Rice and rice-based products')
    , (102,1,'Maize and maize-based products')
    , (103,1,'Wheat and wheat-based products')
    ,(2,2, 'Roots, tubers, plantains and their products')
    , (201,2, 'Potato, sweet potato and their products')
    , (202,2, 'Cassava and similar roots (excluding taro) and their products')
    ,(3,3, 'Pulses, seeds and nuts and their products')
    , (301,3, 'Pulses (excluding soybeans) and their products')
    ,(4,4, 'Milk and milk products')
    , (401,4, 'Milk: fresh and processed')
    , (402,4, 'Fermented milk products')
    , (403,4, 'Cream, whey and any other milk products excluding fermented milk products and cheese')
    , (404,4, 'Cheese')
    ,(5,5, 'Eggs and their products')
    ,(6,6, 'Fish, shellfish and their products')
    , (601,6, 'Freshwater fish (excluding offal)')
    ,(7,7, 'Meat and meat products')
    , (701,7, 'Offal - all types')
    , (702,7, 'Mammals, reptiles and amphibians (excluding offal)')
    ,(8,8, 'Insects, grubs and their products')
    ,(9,9, 'Vegetables and their products')
    ,(10,10, 'Fruits and their products')
    , (1002,10, 'Fruits: fresh')
    ,(11,11, 'Fats and oils')
    ,(12,12, 'Sweets and sugars')
    ,(13,13, 'Spices and condiments')
    ,(14,14, 'Beverages')
    ,(15,15, 'Foods for particular nutritional uses')
    ,(17,17, 'Food additives')
    ,(18,18, 'Composite dishes')
    ,(19,19, 'Savoury snacks')

**Comment by andy-bevan** [comment]
Example values from CSV files:

2006	Cereals	
2019	Cereals, other and products	2006
2093	Wheat and products	2006

**Comment by andy-bevan** [comment]
@bgsandan - is this still even an issue now that the initial duplicates have been removed?

**Comment by LuciaSegovia** [comment]
I am sorry @andy-bevan, but I am not sure if I am following what is going on. Is this an issue of misalignment between IMPACT model and food composition data food groups names?

**Comment by andy-bevan** [comment]
No worries - lets see if Andy can shed any light...?

> I am sorry @andy-bevan, but I am not sure if I am following what is going on. Is this an issue of misalignment between IMPACT model and food composition data food groups names?

**Comment by bgsandan** [comment]
@andy-bevan - Sorry just catching up on this.  So when you say "is this still even an issue now that the initial duplicates have been removed?"  does that mean that the initial issue with multiple versions of essentially the same string with differences in capitalisation in the treemap (as above screenshot) no longer occurs?

Re: IMPACT and FCT food groups being different.  Not a deal breaker for closing this issue but we should look to consolidate these (i.e. get the impact groups to match to existing FCT groups).  That can be a separate/new issue though

**Comment by bgsandan** [comment]
@andy-bevan - Sorry just catching up on this.  So when you say "is this still even an issue now that the initial duplicates have been removed?"  does that mean that the initial issue with multiple versions of essentially the same string with differences in capitalisation in the treemap (as above screenshot) no longer occurs?

Re: IMPACT and FCT food groups being different.  Not a deal breaker for closing this issue but we should look to consolidate these (i.e. get the impact groups to match to existing FCT groups).  That can be a separate/new issue though

**Comment by bgsandan** [comment]
@andy-bevan - Sorry just catching up on this.  So when you say "is this still even an issue now that the initial duplicates have been removed?"  does that mean that the initial issue with multiple versions of essentially the same string with differences in capitalisation in the treemap (as above screenshot) no longer occurs?

Re: IMPACT and FCT food groups being different.  Not a deal breaker for closing this issue but we should look to consolidate these (i.e. get the impact groups to match to existing FCT groups).  That can be a separate/new issue though

**Comment by andy-bevan** [comment]
Yes to the first question - those obvious duplicate/typos are resolved. I'll close the issue.
