### ISSUE TITLE
Household Member demographic data

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#3]
The code for that describes members of a household can be found at https://github.com/micronutrientsupport/bmgf-maps/blob/dev/db/objects/V0.1.0.500__Household_member.sql
So far we have:
- id number of the household this person belongs to
- sex (male or female)
- age (in years, integer) 
- person is a smoker, yes/no
- person (child) is being breastfed, yes/no

Questions:

1. For age, is simply recording the number of years enough, or do we need more granularity, e.g. for recording children's ages?
2. Are any of these attributes not needed for the project, or do they need to be changed?
3. What attributes are we missing that need to be included in the project? The MSAccess databas mlawi_IH3_200804 has several more attributes for demographics, e.g. "birthplace", "marital_status", etc. Do we need any of those, for example?

**Comment by fannymawbey** [comment]
Thanks for that. A few comments
- age should be in months for children until 5 years old (until 59 months), and in years for adult. In summary tables, age should be presented in age group (I can give more details on that)
- Usually to describe a population, we report other types of information like wealth quintile, residence (urban or rural), regions.
- I don't have strong opinion on smoking. It's good to have but I don't think I would put it in a first description table
- Breastfeeding is important to know yes. I won't have the information in all micronutrient surveys but I think it's good to have it in the table.

Have you asked their opinions to other team members?

**Comment by rbroth** [comment]
>  wealth quintile, residence (urban or rural), regions

Those sound like attributes of the household as a whole, rather than the individual people inside of it. I think I'll open a separate issue for those.

@LuciaSegovia @kmtang Any comments to add?

**Comment by LuciaSegovia** [comment]
@kmtang what do you think? Maybe education level and fever and/or anaemia status?

**Comment by fannymawbey** [comment]
Agree with level of education. It can be at the individual level and/or the household level, as some countries choose 'level of education of the head of household'
I would not put fever and anaemia here (a bit too clinical)
