### ISSUE TITLE
CI not correctly loading the household_consumption table

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#305]
Household consumption table is empty on DB builds.

Following message (non-failing) appears in the CI logs:

![image](https://user-images.githubusercontent.com/39411049/151567976-32a47fd2-2434-4a80-b000-8f5ae408c12e.png)

**Comment by rbroth** [comment]
problem is that WAFCT is not being loaded, mena s this entry isn't being loaded:
```
12_012,"Juice, canned or bottled, sweetened (e.g. apple)",23670.01.02,flavoured ice,Other foods,sugar (raw equivalent) and products,medium,WAFCT,"DK2(194), US28(09016)",87.9,48,203,NA,0.1,0.1,0,0,0,0,11.5,0.2,0.2,9,0.3,5,6,80,10,0.04,0.01,NA,NA,NA,0,0.02,0.02,0.1,0.03,0,0,0,NA,NA,1,0,0.01,NA
```

Presumably if we fix this entry there will be other entries that will break

**Comment by andy-bevan** [comment]
This error seems to have been fixed as it is no longer occurring on the master branch. @bgsandan Can you confirm?

**Comment by bgsandan** [comment]
I suspect that this issue may have gone away with the reduction in FCTs being loaded into the system.  Happy to close this issue for now, but we will see if it re-rears it's head once we've properly cracked the whole FCT matching piece
