### ISSUE TITLE
Add "region" to countries table

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#34]
super-national group of countries

**Comment by rbroth** [comment]
@bgsandan can I find the list of these regions online?

**Comment by bgsandan** [comment]
@rroth https://unstats.un.org/unsd/methodology/m49/ and Click Geographic Regions

Pretty graphic version at https://en.m.wikipedia.org/wiki/United_Nations_geoscheme_for_Africa

**Comment by bgsandan** [comment]
Future project scope not just Africa so maybe parent region table?

**Comment by bgsandan** [comment]
But can be populated for now with just the above 6 regions

**Comment by rbroth** [comment]
ugh, the scheme mixed "intermediate regions" and "sub regions" (northern africa is a subregion, the other ones are intermediates). Yuck. Putting them all together for now

**Comment by rbroth** [comment]
have added column, table and data
