### ISSUE TITLE
Best practice for returning GeoJSON from countries

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#38]
Currently have created a simple view on the country table which utilises ST_AsGeoJSON.  This may not be most performant:

1. Would a dynamic column on the country table be more performant?

2. Current view is not a materialized view (syntax doesn't support `CREATE OR REPLACE`.  What is best means of creating (or replacing) a materialized view in a repeatable manner

**Comment by rbroth** [comment]
Re point 2, it might be possible to use `DROP IF EXISTS` + `CREATE` (speculating off the top of my head)
