### ISSUE TITLE
List of nutrients

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#40]
Can you all please have a look at these nutrients and see if we want to remove any? E.g. two values for vitA?

https://github.com/micronutrientsupport/database-architecture/blob/develop/db/objects/fooditem/R__fooditem-comments.sql

**Comment by LuciaSegovia** [comment]
To be removed: (@kmtang do you agree?)

TotalCHOforUDB; Totalsugars_in_g; Addedsugar_in_g; Starch_in_g; VitaminA_in_RE_in_mcg

To be changed:

EnergyCalculated_in_kCal --> Energy_in kCal (unless we are actually calculating the Energy)
EnergyCalculate_in_kJ --> Energy_in_kJ

Totalfibre_in_g                IS ' ';
to
Fibre_in_g                       IS 'The total dietary fibre content of this food item (determined by multiple methods), in grams per 100g'

Folicacid_in_mcg               IS 'The Folic Acid content of this food item, in micrograms per 100g' 
to
Folate_in mcg          IS 'The total folate content of this food item, including food folate and synthetic folate, in micrograms per 100g'

**Comment by kmtang** [comment]
Yes @LuciaSegovia agreed with your modifications. 

One quick question for @LuciaSegovia, why does the  FCT present folic acid instead of folate? Is it like that for all FCTs?

**Comment by LuciaSegovia** [comment]
For some reason, in MAFOODS they use folate and folic acid as the same thing. I am assuming that it is total folate because it make no sense that they are reporting folic acid only. 

So, yes, names in general, and particularly for some nutrients in most FCTs are a bit...inconsistent. That's why I had renamed all the variables of each FCT to keep it consistent, by using the tagnames defined by INFOOD/FAO.

**Comment by rbroth** [comment]
Can you guys clarify the difference between foalte and folic acid? Is it reasonable to assume that they are synonyms? Which one(s) shall we use and which discard?

**Comment by rbroth** [comment]
The Malawi FCT has folic acid, hence why I put that into the current nutrient list

**Comment by rbroth** [comment]
will rename folic acid to folate

**Comment by LuciaSegovia** [comment]
Sorry @rbroth, I forgot to clarify that you need to rename folic acid to folate for Malawi FCT, not for all FCTs.

**Comment by bgsandan** [comment]
@LouiseAnder - Is it possible to comment on this, noting the existing comments from Lucia and Kevin.  Looking at the list of micronutrients that we will both store e.g. composition data for, and also allow the user to select as a nutrient of interest in the front-end UI.  

Keen to get this tied down now so we can push on, ideally finalised but even if things do end up changing down the line, then at least mainly there

**Comment by LouiseAnder** [comment]
@bgsandan  @rbroth  may I check there is a d/b table which is something like:

MN ID | MN name | MN units | MN description - which could be populated

Ca | Calcium | mg per 100 g DM | Calcium (Ca) measured in mg per 100 g dry matter (DM)

Where MN stands for micronutrient (an alternative to this to include macronutrients is fine, this for the gist of the layout)

If so, I think we start with the nutrients in the Malawi FCT and then inspect successive FCTs on loading and add those in. That would be type of functionality to build towards with BYO data users in mind??

**Comment by LouiseAnder** [comment]
What this may not quite work for is the food fortification options... but I haven't fully thought that through

**Comment by bgsandan** [comment]
@LouiseAnder - yes there will likely be something like that, for population of the various dialogue options etc.

@rbroth - the debate about how we marry that sort of structure as per PR #43 with the column headings required in the fooditem table is (I think) still open for debate, but I suggest we go with some variant of the table in that PR (with your recommended corrections) with data rows that match the nutrients in the `fooditem` table and go from there?

Or do you think this is something more fundamental we need to sort out now?  Happy to jump on a zoom call if you think it would help.  We will obviously need to be able to provide users with a list of MN to select from, but also then use that to return the appropriate data columns from the consumption view when requested by a user...

**Comment by LouiseAnder** [comment]
Also happy to zoom @rbroth  and @bgsandan

**Comment by rbroth** [comment]
results of zoom call: current structure (fodoitem table with micronutrients in columns + micronutrient table with micronutrient metadata) is fine. Changes to be made: @bgsandan to add another column to micronutrients table of PR #43 with "column_name" or similar, which contains the name of the corresponding column in the fooditem table
