### ISSUE TITLE
Attribute: Confidence in matching

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#48]
We want a way to indicate 

- how confident we are in how we have matched our data to Foodex2 i.e. how sure are we that when we match an item in a consumption table to a foodex2 value that the two correspond, and 
- how sure are we that when match a fooditem in a food consumption table to foodex2 that the two actually correspond

**Comment by rbroth** [comment]
Available values (e.g. "low", "medium", "high") to be determined by @LuciaSegovia.

Default values to be "we are super confident in this match"

**Comment by rbroth** [comment]
similar to #51

**Comment by bgsandan** [comment]
Resolved by `food_genus_confidence` field
