### ISSUE TITLE
fallback mn data

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#49]
In the case that 

You have a fooditem 
and it is missing a micronutrient property
,and there are no other fooditems in any food compsotion tabes with the same foodex2 label, what do we do?

- show "data missing" to the user and something like 3.23% of users calorific intake has unknow mn data
- figure out some way of matching with somewhere else in foodex2

**Comment by rbroth** [comment]
Decision: show "data is missing"

**Comment by bgsandan** [comment]
Resolved by FCT prioritisation match algorithm
