### ISSUE TITLE
Foodex as a separate table?

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#56]
We will want to be able to get the hierarchic parent groups for various fooditems for display. e.g. Cereals->Grains->Teff.  This may have a bearing on the discussions we had over #50.

As the foodex structure had its own semantic value, it may be better to exist as its own table with the fooditem and consumption tables referencing it?

**Comment by bgsandan** [comment]
FYI @rbroth

**Comment by rbroth** [comment]
I was thinking about that earlier in relation to the MN consumption views. Yes, agreed, separate foodex2 table. But a fooditem will still only have 1 corresponding foodex2 item, correct? Would be very messy otherwise. 

Also, I recall foodex2 having a very complicated structure, with different items having different hierarchies, and some items having sub-items. To what degree do we want to implement this?

**Comment by bgsandan** [comment]
Correct 1:1 mapping to the foodex items i beleive. 

 Re: the foodex2 structure, I'm not sure I know the details of how it is structured.  Maybe one for @LouiseAnder as to how the names will be displayed.  If we can ~~coerce~~ persuade the data to fit into a 'simple' e.g. 3 layer hierarchy then that wouldn't be too bad whilst still providing benefit for e.g. sorting/filtering name lists of foods and/or for textual display, but don't know how plausible that is

**Comment by rbroth** [comment]
@LuciaSegovia is more familiar with the foodex2 structure, she may have some input. Lucia, do you feel coercing foodex2 into a 3-layer hierarchy is sensible?

**Comment by rbroth** [comment]
For the time being I've implemented the foodex table as simply id + name

**Comment by rbroth** [comment]
- foodex2 code
- foodex2 name
- - foodex2 description
- FAO category
- FAO subcategory 
(as found on http://www.fao.org/gift-individual-food-consumption/methodology/food-groups-and-sub-groups/en/ )

in their individual tables
- confidence in match to foodex2
