### ISSUE TITLE
Create view with sum of nutrient availability across all IMPACT commodities

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#67]
For a given country, nutrient, scenario and year nutrient availability data is provided by IMPACT across a range of commodities.

For simple representations of availability, this needs to be summed for all commodities (for each country/nutrient/scenario/year combination) to give a single value for nutrient availability.  (See main data table in Figma prototype).

Create a view to return these aggregations for the API

**Comment by rbroth** [comment]
Should the nutrient availabilities be per capita? Might be more useful than saying "Zimbabwe consumed 20000kg of Vitamin A in 2018".

Also, can you link directly to the main data table in figma? I've just had a quick look around and I can't seem to find which one you mean

**Comment by bgsandan** [comment]
So the IMPACT data is already per capita.  Think the current data in the DB is kg/capita/year but that will likely want to be updated to be g/capita/day to match the FBS data.  I wouldn't worry too much immediately as that shouldn't affect the data structures/views.  The Figma has the ability to update the units but that will just be applying a scaling factor on the front end.

**Comment by bgsandan** [comment]
So the IMPACT data is already per capita.  Think the current data in the DB is kg/capita/year but that will likely want to be updated to be g/capita/day to match the FBS data.  I wouldn't worry too much immediately as that shouldn't affect the data structures/views.  The Figma has the ability to update the units but that will just be applying a scaling factor on the front end.
