### ISSUE TITLE
Define standardised format for input csv structures for data

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#77]
Establish standardised structure for

* FCT
* Consumption data
* Other data formats?

both for data import and in preparation for BYOD functionality

**Comment by LuciaSegovia** [comment]
Hi @rbroth and @bgsandan, 

I have uploaded an updated version of fct-regional (the one to be used with FBS) to Teams (WP2 - Data curation>Food Composition Tables

**Comment by LouiseAnder** [comment]
Thanks @LuciaSegovia ! 

Can I just check on 'x' in the " **foodname_originalfct**" field?  Is that _no  match_ or is it _no data_ ?

Nice one :)

**Comment by LuciaSegovia** [comment]
@LouiseAnder it's a 'no data' :)

Thanks!!

**Comment by rbroth** [comment]
A format for a CSV Food Composition table. @LuciaSegovia, have a look and see if it makes sense.

Column Name                |  Description                                                                                                                                                                                                     |
| -----------              |    -------------                                                                                                                                                                                                 |
original_food_id           |    The food ID as it was found in the original Food Composition Table. Kept for informational purposes only                                                                                                      |
original_food_name         |    The food name as it was found in the original Food Composition Table. Kept for informational purposes only                                                                                                    |
food_genus_id              |    The food genus of this food. Will be used for matching, and, in the future, will come from a curated list.                                                                                                    |
food_genus_description     |    DSescription for this food_genus                                                                                                                                                                              |
food_group                 |    The food group for this food_genus.                                                                                                                                                                           |
food_subgroup              |    The food subgroup for this food genus.                                                                                                                                                                        |
food_genus_confidence      |    How confident we are in the matching. Mediums will show a warning to the user, low confidence fooditems won't be used in any calculations at all. Possible values: [ 'High' , 'Medium', 'Low']                |
fct_name                   |    The name (citation text?) for the food composition table from which this fooditem came. For example, 'Gambia Prynand Paul'.                                                                                   |
fct_pub_date               |    The publication date of the FCT, if known                                                                                                                                                                     |
data_reference_name        |  The name of this citation                                                                                                                                                                                       |
data_reference_original_id |  the original id of this citation                                                                                                                                                                                |
data_reference_author      |  The author of the publication from where the nutrient values were derived                                                                                                                                       |
data_reference_publication |   The publication in which the micronutrient contents of this food were found.                                                                                                                                   |
data_reference_isbn        |                                                                                                                                                                                                                  |
data_reference_notes       |                                                                                                                                                                                                                  |
moisture_in_g              |    The moisture content of this food item, in grams per 100g                                                                                                                                                     |
energy_in_kcal             |                                                                                                                                                                                                                  |
energy_in_kj               |                                                                                                                                                                                                                  |
nitrogen_in_g              |    Nitrogen content of this fooditem, in grams per 100g                                                                                                                                                          |
totalprotein_in_g          |    Total Protein Content, in grams per 100g                                                                                                                                                                      |
totalfats_in_g             |    Total Fats, in grams per 100g                                                                                                                                                                                 |
saturatedfa_in_g           |    Saturated Fatty Acids, in grams per 100g                                                                                                                                                                      |
monounsaturatedfa_in_g     |    Monounsaturated Fatty Acids, in grams per 100g                                                                                                                                                                |
polyunsaturatedfa_in_g     |    Polyunsaturated Fatty Acids, in grams per 100g                                                                                                                                                                |
cholesterol_in_mg          |    The Cholesterol content of this food item, in milligrams per 100g                                                                                                                                             |
carbohydrates_in_g         |     Carbohydrates in g per 100g                                                                                                                                                                                  |
fibre_in_g                 |    The total dietary fibre content of this food item (determined by multiple methods), in grams per 100g                                                                                                         |
ash_in_g                   |   (I don't think we really need the ash content of the food? candidate for deletion from the system)                                                                                                             |
ca_in_mg                   |    The Calcium content of this food item, in milligrams per 100g                                                                                                                                                 |
fe_in_mg                   |    The Iron content of this food item, in milligrams per 100g                                                                                                                                                    |
mg_in_mg                   |    The Magnesium content of this food item, in milligrams per 100g                                                                                                                                               |
p_in_mg                    |    The Phosporous content of the food item, in milligrams per 100g                                                                                                                                               |
k_in_mg                    |    The Potassium content of this food item, in milligrams per 100g                                                                                                                                               |
na_in_mg                   |    The Sodium content of this food item, in milligrams per 100g                                                                                                                                                  |
zn_in_mg                   |    The Zinc content of this food item, in milligrams per 100g                                                                                                                                                    |
cu_in_mg                   |    The Copper content of this food item, in milligrams per 100g                                                                                                                                                  |
mn_in_mcg                  |    The Manganese content of this food item, in micrograms per 100g                                                                                                                                               |
i_in_mcg                   |    the Iondine content of this food item, in micrograms per 100g                                                                                                                                                 |
se_in_mcg                  |    The Selenium content of this food item, in micrograms per 100g                                                                                                                                                |
vitamina_in_rae_in_mcg     |    The Vitamin A content of the food, in Retinol Activity Equivalent (RAE), and in micrograms per 100g                                                                                                           |
thiamin_in_mg              |    The Thiamin content of this food item, in milligrams per 100g                                                                                                                                                 |
riboflavin_in_mg           |    The Riboflavin content of this food item, in milligrams per 100g                                                                                                                                              |
niacin_in_mg               |    The Niacin content of this food item, in milligrams per 100g                                                                                                                                                  |
vitaminb6_in_mg            |    The Vitamin B6 content of this food item, in milligrams per 100g                                                                                                                                              |
folicacid_in_mcg           |    The Folic Acid content of this food item, in micrograms per 100g                                                                                                                                              |
folate_in_mcg              |    The total folate content of this food item, including food folate and synthetic folate, in micrograms per 100g                                                                                                |
vitaminb12_in_mcg          |    The Vitamin B12 content of this food item, in micrograms per 100g                                                                                                                                             |
pantothenate_in_mg         |    The Pantothenate content of this food item, in milligrams per 100g                                                                                                                                            |
biotin_in_mcg              |    The Biotin content of this food item, in micrograms per 100g                                                                                                                                                  |
vitaminc_in_mg             |    The Vitamin C content of this food item, in milligrams per 100g                                                                                                                                               |
vitamind_in_mcg            |    The Vitamin D content of this food item, in micrograms per 100g                                                                                                                                               |
vitamine_in_mg             |    The Vitamin E content of this food item, in milligrams per 100g                                                                                                                                               |
phyticacid_in_mg           |    The Phytic Acid content of this food item, in milligrams per 100g                                                                                                                                             |

**Comment by LouiseAnder** [comment]
@rbroth Hi Roman, thank you! Couple of quick Q's.  

Is there any reason the names are all lower case? Also, is it worth having symbols in brackets after names, e.g. Copper (Cu). 

Also, are we fixing the d/base as dry matter (DM) concentrations? If so, I think this is a useful attribute (i.e. 'DM') of the Description. 

NB spelling of iodine and phosphorus.

**Comment by rbroth** [comment]
> Is there any reason the names are all lower case? 
I've copy-pasted the column names directly from the database code, for consistency. This should make importing data easier for me. I think the column names are case-insensitive, but I haven't tested it.

> is it worth having symbols in brackets after names, e.g. Copper (Cu).

We can do that if you think it will make things clearer for people who will bring their own data.

> Also, are we fixing the d/base as dry matter (DM) concentrations? If so, I think this is a useful attribute (i.e. 'DM') of the Description.

I'll add "dry matter" to the description of the nutrients

> NB spelling of iodine and phosphorus.

Will fix

**Comment by LouiseAnder** [comment]
> 
> > Is there any reason the names are all lower case?
> 
> I've copy-pasted the column names directly from the database code, for consistency. This should make importing data easier for me. I think the column names are case-insensitive, but I haven't tested it.

I think it will be 'human readable' if we have capitals where they would be expected, or make reading easier - e.g. **Ca_mcg**, **VitaminE_mcg**. Not a problem how the underpinning database stores these if they are case-insensitive of course - I'm thinking ahead to future data import. 

Also, do we need 'in' in the field names? Hadn't thought of that before. When we are writing these out we'd often use Ca (mg/kg) for instance, and not use 'in'. 

> 
> > is it worth having symbols in brackets after names, e.g. Copper (Cu).
> 
> We can do that if you think it will make things clearer for people who will bring their own data.

I think this will help - some of the more 'obscure' chemical elements do not have chemical symbols which look/sound like an abbreviation of their English name, and it can trip people up if these don't appear to match between the field ID and the description. 

> > Also, are we fixing the d/base as dry matter (DM) concentrations? If so, I think this is a useful attribute (i.e. 'DM') of the Description.
> 
> I'll add "dry matter" to the description of the nutrients
> 
> > NB spelling of iodine and phosphorus.
> 
> Will fix

thanks!

**Comment by rbroth** [comment]
The field names I'm using here are aimed at the MAPS team members for formatting and importing the data that we currently have. These field names are only meant to be used as machine-readable headers for data import. As such, I'm focusing on compatibility, minimizing errors, and ease of programming. 

When it comes time for BYOD, we can write code to import headers that are named whatever we wish

**Comment by LouiseAnder** [comment]
Great, thanks!

**Comment by rbroth** [comment]
@kmtang Could you have a look to see if the below format makes sense and then send me IHS3 data in this format? Also, do we have any other household and individual consumption datasets that we want to import, or just IHS3 and IHS4?

## Household & Intake data

### household: 

| header | description |
| ---    | ----------- |
| original_id                ||
| lat                        ||
| lon                        ||
| urbanity                   ||
| household_expenditure      ||
| wealth_quintile            ||
| survey_id                  | which survey this data is from e.g. 'IHS3'. There'll be some data about the survey itself, but I'll ask for that sepraretly |
| interview_date             ||


### household consumption

| header | description |
| ---    | ----------- |
| food_genus_id         | The food_genus id of the fooditem that was consumed                                                                                                              |
| food_genus_confidence | How confident we are in matching this food to the corresponding food_genus entry [ 'High' , 'Medium', 'Low']                                                     |
| original_food_name    | the original food name, as given by the consumption survey                                                                                                       |
| household_original_id | The original id of the household that consumed the food item                                                                                                     |
| source_of_food        | From where the household obtained the food; if they grew it themselves, bought it at market, or had it gifted to them ['own production', 'bought', 'gifted']     |
| date_consumed         | The date when the fooditem was consumed                                                                                                                          |
| amount_consumed_in_g  | How much of the fooditem was consumed on average per day, in grams                                                                                               |
																																														   

### household member
| header | description |
| ---    | ----------- |
| household_member_original_id |            |
| household_original_id        |            |
| sex                          | ['m', 'f'] |
| age_in_months                |            |
| is_breastfed                 |            |
| is_lactating                 |            |
| is_pregnant                  |            |


###  household member consumption
| header | description |
| ---    | ----------- |
| household_member_id   | The id of the household member that consumed the food item                                                                                                             |
| food_genus_id         | The food_genus id of the fooditem that was consumed                                                                                                                    |
| food_genus_confidence | How confident we are in matching this food to the corresponding food_genus entry                                                                                       |
| source_of_food        | From where the household member obtained the food; if they grew it themselves, bought it at market, or had it gifted to them ['own production', 'bought', 'gifted']    |
| date_consumed         | The date when the fooditem was consumed                                                                                                                                |
| amount_consumed_in_g  | How much of the fooditem was consumed, in grams                                                                                                                        |

**Comment by LuciaSegovia** [comment]
Hi @rbroth and @LouiseAnder, sorry I'm a bit late to this party 

> Also, are we fixing the d/base as dry matter (DM) concentrations? If so, I think this is a useful attribute (i.e. 'DM') of the Description.

Values are not in DM, they are reported in EP (edible portion). 

Regarding the FCT format structure, I was thinking to 'remove' some of the columns with FCT information and to create another dataset (with information only). For example, instead of having one column with the citation and 'orginal' FCT information to create one dataset with all the FCTs information. Something like the Food Data Dictionary but with all the info about the FCTs. Does it make sense? 

Also, you can't remove ash (sorry) it's needed for quality checks :) 

> The field names I'm using here are aimed at the MAPS team members for formatting and importing

Agree, if it's for internal purposes, can we please use lower case 🙏 ?

**Comment by LouiseAnder** [comment]
thanks @LuciaSegovia  - so we should record these as being **Fresh Weight (FW) edible portion (EP)** ? This will make a huge difference to the results loaded and calculated outputs, and be an area where its always easy to make a mistake. So, I think it is useful to be explicit about this, however tediously repetitive it makes the description. What do you think?

**Comment by LuciaSegovia** [comment]
I couldn't agree more @LouiseAnder! And, it would become essential when we start importing GeoNutrition type data!

**Comment by rbroth** [comment]
@LuciaSegovia We're looking at importing some FCT data. Could you rename the columns of the csv files in "WP2/FoodCompositon Tables/Working Files" so to those above?

**Comment by LuciaSegovia** [comment]
Sure @rbroth!

**Comment by rbroth** [comment]
> I have a question, I started with West-Africa FCT (WAFCT), there are some extra variables that are not in the list and there are variables that are in the list that will have a NULL value. For example, _pantothenate_in_mg_ is not reported in WAFCT, while B-caroten is reported but not included in our list of variables. What should I do?
> 
> If it's not too annoying, I would like to keep ALL variables, otherwise, I will keep all the variables listed above and I will fill the non-existant variables (i.e. _pantothenate_in_mg_) with `NA`.


We want every csv to conform to our column list (and have the same order), so if a dataset does not report a micronutrient, add a column with the title of the missing micronutrient and fille the column values blank/NULL/'NA'.

If a dataset reports a nutrient that we are not interested in, delete the column.

> > Regarding the FCT format structure, I was thinking to 'remove' some of the columns with FCT information and to create another dataset (with information only). For example, instead of having one column with the citation and 'orginal' FCT information to create one dataset with all the FCTs information. Something like the Food Data Dictionary but with all the info about the FCTs. Does it make sense?
> 
> Can I remove those variables?

Yes, much better idea. I will modify the comment  food composition table format above and add a new comment with formats for the FCT source and citation data


> Finally, I will name the files MAPS_[FCT]_vx.x.csv', so the most 'advanced version' is the one with the variables updated :)

Excellent idea!

**Comment by LuciaSegovia** [comment]
Great! Do you need it urgently or by the end of the week is fine?

**Comment by rbroth** [comment]
@spenny-liam is working on a script to import the data, I assume end of week should be fine?

**Comment by LuciaSegovia** [comment]
Hi @rbroth, 

These are the variables I would "remove" from the FCT and used to create the "FCT-metadata dataset". 

ColumnName| Description
-- | --
fct_pub_date | The publication date of the FCT, if known
data_reference_name | The name of this citation
data_reference_original_id | the original id of this citation
data_reference_author | The author of the publication from where the nutrient values were derived
data_reference_publication | The publication in which the micronutrient contents of this food were   found.
data_reference_isbn |  
data_reference_notes |

**Comment by rbroth** [comment]
That look good, but we'll need to keep the `data_reference_original_id`, in order to link the individual food item with its citation

**Comment by LuciaSegovia** [comment]
No problem, but I am not sure if I know what you mean by "individual food item with its citation" 😅

**Comment by spenny-liam** [comment]
Hi @LuciaSegovia and @rbroth . So should i wait until the FCT files are in a new format before i start trying to import them?

**Comment by rbroth** [comment]
data_reference means the citation of the journal article where that food composition for that particular food item was taken from. E.g. food item "Mars Bar, malawian edition" would be found in the "Malawi Food Composition Table 2019". The Malawi FCT 2019 would have an endnote next to the  "Mars Bar, malawian edition" entry to it bibliography, where it would say "37: Johnson and Bobson, 'The vitamin content of African chocolate bars', International Journal of Chocolate, 2013".

| field        |           example                                            |
|----------------------------|--------------------------------------------------------------------------------|
| data_reference_name        |   The vitamin content of African chocolate bars                                                    |
| data_reference_original_id | 37                                               |
| data_reference_author      | Johnson and Bobson      |
| data_reference_publication | International Journal of Chocolate |
| data_reference_isbn        |                                                                                |
| data_reference_notes       |                                                                                |

**Comment by LuciaSegovia** [comment]
Ok, I know what you mean, it's going to be messier than that beautiful Mars example (as usual), but it's fine :) Thanks!

@spenny-liam are you going to import all of them or do you have any prefereces?

**Comment by spenny-liam** [comment]
No preference - If they are all going to have exactly the same columns then can import them all in the same way. Once you have one (any) file in the correct format then i can get that imported and expect the rest to work in the same way.

**Comment by LuciaSegovia** [comment]
I've just uploaded on to "WP2/FoodCompositon Tables/Working Files" , "MAPS_WAFCT_v01.1.csv". Let me know if it works fine and I will do the same with the rest :)

**Comment by spenny-liam** [comment]
> I've just uploaded on to "WP2/FoodCompositon Tables/Working Files" , "MAPS_WAFCT_v01.1.csv". Let me know if it works fine and I will do the same with the rest :)

Yes that is perfect and fits straight into the database tables. What is the current plan going forward with the food_genus, food_group and food_subgroup?

**Comment by LuciaSegovia** [comment]
Cool! Foor food_genus, I can provide some values for Malawi FCT (MAFOODS), but I will be "filling" them as we need.

**Comment by spenny-liam** [comment]
@LuciaSegovia do files exist yet for the "FCT-metadata dataset"? if so where are they and what are they called?

**Comment by LuciaSegovia** [comment]
@spenny-liam, I haven't done it yet. When do you need it?

**Comment by spenny-liam** [comment]
> @spenny-liam, I haven't done it yet. When do you need it?

No urgency. i'll just get everything in as it is for now.

**Comment by spenny-liam** [comment]
> These are the variables I would "remove" from the FCT and used to create the "FCT-metadata dataset".
> 
> ColumnName	Description
> fct_pub_date	The publication date of the FCT, if known
> data_reference_name	The name of this citation
> data_reference_original_id	the original id of this citation
> data_reference_author	The author of the publication from where the nutrient values were derived
> data_reference_publication	The publication in which the micronutrient contents of this food were found.
> data_reference_isbn	 
> data_reference_notes

Are you still happy that this should be the structure of the metadata? Looks fine to me. We will rename "data_reference" -> "citation" as per issue #137 , but other than that are we going to have the same columns as above?

**Comment by LuciaSegovia** [comment]
@spenny-liam, I am doing a "reconciliation" of the variable names together with the #138

**Comment by LuciaSegovia** [comment]
Can we keep it simple as it's reported in the original FCT? 


fct_name | citation_original_id | citation_name
 -- | -- | --
West-Africa FCT| 01BR | Rodriguez-Amaya,   D.B., Kimura, M. & Amaya-Farfan, J. 2008. Fontes Brasileiras de carotenóides: tabela brasileira de   composição de carotenóides em alimentos. Brasilia,   Ministério do Meio Ambiente. (also available at   http://www.mma.gov.br/estruturas/sbf_agrobio/_publicacao/89_publicacao09032009113306.pdf).
West-Africa FCT | 01CH | Li, R., Xia, Q.,   Tang, M., Zhao, S., Chen, W., Lei, X. & Bai, X. 2012.   Chemical composition of Chinese palm fruit and chemical properties of the oil   extracts. African Journal of Biotechnology, 11(39): 9377–9382.
West-Africa FCT | 01FG | Onyekwelu, J.C.,   Oyewale, O., Stimm, B. & Mosandl, R. 2015.   Antioxidant, nutritional and anti-nutritional composition of Garcinia kola and Chrysophyllum albidum from   rainforest ecosystem of Ondo State, Nigeria. Journal   of Forestry Research, 26(2): 417–424.

**Comment by rbroth** [comment]
I have no problem with that if it makes your work easier. We may have a requirement in the future to format the citations nicely on the frontend, but for now that seems perfectly sensible to me

**Comment by LuciaSegovia** [comment]
Perfect. I agree, I would put a note on that for 'my future self' to-do list :) 

@spenny-liam I added a new version of MAPS_MAFOODS with some food_genus, let me know if it's fine!

**Comment by LuciaSegovia** [comment]
@rbroth or @spenny-liam can we double check the food_genus columns? Because, I think I have one more level of detail than you do.

**Comment by spenny-liam** [comment]
> @rbroth or @spenny-liam can we double check the food_genus columns? Because, I think I have one more level of detail than you do.

Yes i can see a food_subgroup - which we don't have in the database. We will have to figure out whether that is needed for the system, and if so, how we will store that.

**Comment by spenny-liam** [comment]
For reference, columns in MAPS_MAFOODS_v1.4:

original_food_id | original_food_name | food_genus_id | food_genus_description | food_group | food_subgroup | food_genus_confidence | fct_name | data_reference_original_id | moisture_in_g | energy_in_kcal | energy_in_kj | nitrogen_in_g | totalprotein_in_g | totalfats_in_g | saturatedfa_in_g | monounsaturatedfa_in_g | polyunsaturatedfa_in_g | cholesterol_in_mg | carbohydrates_in_g | fibre_in_g | ash_in_g | ca_in_mg | fe_in_mg | mg_in_mg | p_in_mg | k_in_mg | na_in_mg | zn_in_mg | cu_in_mg | mn_in_mcg | i_in_mcg | se_in_mcg | vitamina_in_rae_in_mcg | thiamin_in_mg | riboflavin_in_mg | niacin_in_mg | vitaminb6_in_mg | folicacid_in_mcg | folate_in_mcg | vitaminb12_in_mcg | pantothenate_in_mg | biotin_in_mcg | vitaminc_in_mg | vitamind_in_mcg | vitamine_in_mg | phyticacid_in_mg
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by LuciaSegovia** [comment]
> > @rbroth or @spenny-liam can we double check the food_genus columns? Because, I think I have one more level of detail than you do.
> 
> Yes i can see a food_subgroup - which we don't have in the database. We will have to figure out whether that is needed for the system, and if so, how we will store that.

And, on top of that I have one more subgroup that I did not add it there...

**Comment by spenny-liam** [comment]
@LuciaSegovia I have added in the functionality for subgroup - #139. Hopefully no more levels for now so we can just get the data in. One question i have right now: Which column in your most recent csv identifies a food_genus name? There is id and description but no name unless it is one of the first two columns

**Comment by LuciaSegovia** [comment]
> @LuciaSegovia I have added in the functionality for subgroup - #139. Hopefully no more levels for now so we can just get the data in.

That's fine. 



> It may be that we expected too much detail, and that there is only one description/name and not both

Correct! description is the "name"

**Comment by spenny-liam** [comment]
@LuciaSegovia Sorry to be a pain but would it be possible for you to make the text for the food_group and food_subgroup consistent with the FAO groups here http://www.fao.org/gift-individual-food-consumption/methodology/food-groups-and-sub-groups/en/

Small differences such as "Roots and Tubers" and "Roots, tubers, plantains and their products" could cause problems and confusion later on. The UN and others have already done some of the hard work for us in arranging these groups so i think it would be sensible for us to use them.

**Comment by spenny-liam** [comment]
> @LuciaSegovia Sorry to be a pain but would it be possible for you to make the text for the food_group and food_subgroup consistent with the FAO groups here http://www.fao.org/gift-individual-food-consumption/methodology/food-groups-and-sub-groups/en/
> 
> Small differences such as "Roots and Tubers" and "Roots, tubers, plantains and their products" could cause problems and confusion later on. The UN and others have already done some of the hard work for us in arranging these groups so i think it would be sensible for us to use them.

Nevermind about this. Spoke to everyone else about it and turns out this has all been discussed already. I will automatically create groups and subgroups from what you have given me.

**Comment by LouiseAnder** [comment]
thanks both! @LuciaSegovia  if you could 'walk' @spenny-liam  through your decisions in a quick meeting, I think that would really help?

**Comment by LuciaSegovia** [comment]
No problem @LouiseAnder! @spenny-liam I'm quite free today, so if you want to have a chat after 12noon, let me know!

**Comment by rbroth** [comment]
FYI, the "data_reference" fields will be renamed to "citation" to improve clarity. https://github.com/micronutrientsupport/database-architecture/issues/137

**Comment by LuciaSegovia** [comment]
Hi @rbroth and @spenny-liam, 

Do you have a data format preference for Food Balance Sheet? :)

**Comment by spenny-liam** [comment]
> Hi @rbroth and @spenny-liam,
> 
> Do you have a data format preference for Food Balance Sheet? :)

Hi @LuciaSegovia Sorry for the slow reply. I will talk to Roman about this today and get back to you.

**Comment by rbroth** [comment]
I've added issue #175 to keep notes about the consumption tables, since the comments here are getting rather long.

**Comment by rbroth** [comment]
To close this issue: consolidate all the csv formats discussed here and put them into markdown files/template csv files in the rpository itself. A folder already exists in /doc/import-templates

**Comment by andy-bevan** [comment]
> To close this issue: consolidate all the csv formats discussed here and put them into markdown files/template csv files in the rpository itself. A folder already exists in /doc/import-templates

This is done and can be closed when merged on the db-test-project.
