### ISSUE TITLE
Is time-of-day in-scope

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#8]
Do we want to record the time-of-day or the meal (breakfast/lunch/dinner) for food consumption/recall data?

**Comment by LouiseAnder** [comment]
Yes, if recorded in the original dataset. I think this will be associated mostly with 24-hr recall data, won't it?

**Comment by rbroth** [comment]
I'm not sure, I just wanted to make sure that it's in-scope
