### ISSUE TITLE
Use country-consumption if household/individual consumption data does not exist

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#89]
As an end user, I want to see the most detailed data for a country's consumption. The country-level data is ok, but quite coarse; if possible, I want to use household consumption data derived from household surveys instead too know what the average Micronutrient consumption of a country is.

Have a view that shows the micronutrient intake per capita per year for each country, based on household consumption survey data or, if the household consumption survey data is not available for that country, use country consumption data instead

**Comment by rbroth** [comment]
@bgsandan let me know if this accurately reflects point 4 of #88. Seems like quite a substantial change for view `country_intake`

**Comment by bgsandan** [comment]
Hi @rbroth.  Sorry for any confusion.  I may not have made my intention clear in the word doc.

The purpose of point 4 was not to provide a view of the data, but to provide a view showing what data is available.  So for a given country:

- If there is a household survey that covers that country we should return the id of that, 
- if there are multiple household surveys then the most recent should be returned (inverse sort by year, algorithm may change down the line)
- If there are now household surveys then show any country level data (from country_consumption_source) again inverse sort by year

So essentially the view will be a lookup table that gives:  country, data_id, data_type (field names TBC) that allows the front-end / API to display to the user what we think is the best dataset for that country, at which point the data can be fetched from `household_intake` or `country_intake` depending on the value of `data_type` using the id returned.

Does that make sense?  `country_intake` and `household_intake` shouldn't need to change.  This is more about signposting which is best to look at by default for a given country in Quick MAPS.  Down the line, a user may then be able to explictly select a different dataset (e.g. lower resolution country data, to allow comparison across nations).

Any queries, just shout :)

**Comment by rbroth** [comment]
Made new issue for this #90
