### ISSUE TITLE
Household Demographic data

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#9]
Households (defined as a house and the group of people that live in it as a unit) have data associated with them that is separate from the attributes of individual persons. For example:

- location of the house (lat/lon)
- What admin region the household belongs to (and whether that region is urban or rural)
- size of the household (how many people live there)
- wealth quintile 

What other demographic data is there that we want to include? For example, the Malawi IHS3 access db includes "head of household"; what does that mean? are we including it?

**Comment by LuciaSegovia** [comment]
As far as I know, head of household is the person in charge of that household and yes, we want to include it. But I guess, @kmtang is better person to reply to this :)

**Comment by kmtang** [comment]
A couple things:

Yeah head of HH is a subjectively reported measure, but generally it is the head male (father). In cases where the head male is absent, the head female (mother) usually takes the position. In my opinion, its not super important data for our purposes so I wouldn't include it.

Wealth quintile is an indexed measure that we/the World Bank creates ourselves using the collected data. There are multiple ways of doing it, presented here in the IHS3 they use household expenditures (i.e. how much money the household spent in the last XX days/months). Other methods are expected to calculate wealth/socioeconomic position (SEP) differently. What's important for now is that there may be multiple variables describing HH wealth/SEP so it would be great if we could plan for that.

Size of HH is important, number of adult male equivalents (which is an adjustment of the size of the household based micronutrient need in reference to the adult male) is also equally important. I'd recommend adding both.

**Comment by rbroth** [comment]
Leaving head of household out makes things easier.

Any idea what those multiple wealth variables would be? They should be straightforward to add in the future.

I'm planning on calculating household size dynamically; it's my understanding that we'll have an itemised list of every member of a household for every household, so we will never be in the situation where we have data on a household but not on individual household members. Can you confirm that that's correct?

**Comment by LuciaSegovia** [comment]
Sorry to ruin your morning, but I believe that we will have information at individual level (i.e. age) but we will not have information on food consumption at individual level (for household surveys). 

Then, since we need to add information at individual level anyway, can we keep head of household? 

For wealth variable, I am not sure, if we are going to use a combined metric (@kmtang ) or we are going to use household income?

**Comment by rbroth** [comment]
Yes, sorry, I meant that we'll always have age, sex and adult equivalency data for individual members, even if we only have aggregated food consumption data for the household.

**Comment by fannymawbey** [comment]
I've seen a micronutrient survey report recently reporting results depending on head of household, so I guess it's important for some countries. I would keep it.

Yes, wealth quintiles can be calculated in different ways (household expenditures, household income, assets and I'm sure there are others).

**Comment by LuciaSegovia** [comment]
@fannymawbey do you think that we can decide on one way to calculate wealth or it needs to be flexible?

**Comment by fannymawbey** [comment]
@LuciaSegovia I think better to be flexible. In some countries being rich would mean to own agricultural land, in other it would be to earn a certain amount a cash.
Question: if the wealth quintile is already given in the dataset (for example the dataset includes a variable wealth quintiles), do we want to recalculate it or use what's there?

**Comment by LuciaSegovia** [comment]
Good question. I think it would depend on two things: 1) are we going to need/use those variables in MAPS? or are we adding them just to re-calculate the wealth quintile?. 2) how are wealth quintile calculated? Is it just 'easy' formulae or does it need to be modelled? 

So, I guess if we are not going to use those variables in the tool and the calculations are quite complex, then I suggest to take the wealth quintile and we can run some 'quality check' before importing to make sure that the calculations are error-free. But, happy to discuss :)
