### ISSUE TITLE
Top 20 food items that contribute to MN availability (country consumption data)

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#91]
For a given micronutrient in a given country:
Return top 20 food items (food_genus name) for supply of MN of choice .

E.g: 
a country consumes 1000 kg of Vitamin A. Of this, 20% if Vitamin A are derived from the consumption of eggs, the highest proportion. Thus, "Eggs" should be entry 1 on the result

**Comment by rbroth** [comment]
Will we have country consumption data for different years? It would probably make sense to make sure that the view can handle that.
- [ ] GROUP BY consumption_date year

**Comment by bgsandan** [comment]
Yes, though for greater flexibility this is why I put in the country_consumption_source field and used that as a group by field.  Means that if we had two sets of data for the same year and/or the timeframes change then it still works.  Also mirrors the fooditem tables which have their own fct_source table

**Comment by bgsandan** [comment]
The `country_intake` view has group by clauses on both the fct_source_id and the data_source id from the country_consumption_source table as a reference point
