### ISSUE TITLE
Breakdown of food group contribution to dietary supply of given MN across the year

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#98]
For all households, aggregate the dietary supply of the chosen MN to the food_group column of the food_genus table.  Return this aggregation broken down across the months of the year (i.e. to allow the seasonality of vitamin A supply from mangoes to become apparent).  

Return raw value and as a percentage of total.

Example output of the visualisation that this view should support (all bars should reach 100%):

<img width="486" alt="Screenshot 2021-03-02 at 13 34 47" src="https://user-images.githubusercontent.com/39411049/109656867-c4915a80-7b5c-11eb-97c5-4f17b421f7e3.png">

NB. only for household level consumption data as that has high enough resolution of data collection

**Comment by rbroth** [comment]
Will we need to break this down by survey or region? Because seasonality and foods might be different in India vs Southern Africa

**Comment by bgsandan** [comment]
In the first instance, it should break down the same way as the other views - i.e. by fct_source_id and survey_id

That way when the user selects a country, the `diet-data-sources` view returns the consumption_id and composition_id which can then be used to get the monthly breakdown for that FCT/survey pairing (which will indeed differ across geographies etc)

**Comment by rbroth** [comment]
Looks like we haven't actually got any household data with `date_consumed` in the db yet. I'm assuming we just want to use to use the date of the interview as a proxy.
